### ISSUE TITLE
Error while loading Nous-Capybara-34B

### ISSUE THREAD

**Issue by eramax** [ollama/ollama#1139]
I tried to run https://huggingface.co/TheBloke/Nous-Capybara-34B-GGUF
using this modelfile
```
FROM ./nous-capybara-34b.Q3_K_S.gguf
TEMPLATE """USER: {{ .Prompt }} ASSISTANT:"""
PARAMETER num_ctx 200000
PARAMETER stop "USER"
PARAMETER stop "ASSISTANT"
```

I got this error
```
Error: llama runner process has terminated
```
I have 32GB RAM and 1050 TI GPU with 4GB.

**Comment by MostlyKIGuess** [comment]
I think it might be due to the fact you got seg fault as 4FB GPU isn't really enough to handle a 34 b model, does your 7b model run fine?

then it is for sure that but if not try removing this model and reinstalling it with some different system format, basically create a special model

- If you want any help just ping me, would help you out in creating a model

**Comment by BruceMacD** [comment]
Thanks for the report, this was an issue with memory allocation in this version of ollama. New versions will now fallback to CPU when there is not enough memory available on the GPU. So if anyone sees a similar error try updating to the latest release.

Resolving this one for now as I believe it is solved.
