### ISSUE TITLE
Ollama with multiple GPUs

### ISSUE THREAD

**Issue by technovangelist** [ollama/ollama#1288]
If you are running ollama on a machine with multiple GPUs, inference will be slower than the same machine with one gpu but it will still be faster than the same machine with no gpu. The benefit of multiple GPUs is access to more video memory, allowing for larger models or more of the model to be processed by the GPU. 

BUT if you have enough video memory on the first gpu, we should use only the one gpu, to ensure that perf is as fast as possible. Otherwise it is slower for no good reason. 

And if possible, it would be great to identify the faster gpu and use that first.

**Comment by peteygao** [comment]
This is because the model checkpoint synchronisation is dependent on the slowest GPU running in the cluster.

So you're correct, you can utilise increased VRAM distributed across all the GPUs, but the inference speed will be bottlenecked by the speed of the _slowest_ GPU.

This should be a separate feature request: Specifying which GPUs to use when there are multiple GPUs attached to the machine.

**Comment by peteygao** [comment]
I was assuming you were using a heterogenous GPU setup given your last sentence about the "identify the faster GPU".

If your model can fit inside a single GPU, that will yield the maximum performance since there's zero latency penalty from synchronising with other GPUs.

Multi-GPU setup is only useful in two scenarios:
1) Increasing throughput by having parallel inferences, 1 inference per GPU (assuming the model fits into the VRAM entirely)
2) Ability to use larger parameter models by splitting the tensors across the GPUs--you'll have less throughput compared to a single "large" GPU, but at least you can run larger models. You lose less throughput if the GPUs are utilising NVLink rather than the PCI-e bus, but I guess you are using a cloud provider and have no way of controlling the physical hardware.

**Comment by dhiltgen** [comment]
Let's track this optimization with #1656
