### ISSUE TITLE
 Feature Request:  🛠️ Configurable Option to Prevent Automatic Activation of ollama.service on Linux

### ISSUE THREAD

**Issue by Samk13** [ollama/ollama#1352]
Running on WSL2 Ubuntu 22

I'd like to inquire if there's an existing configuration option within Ollama that can stop the automatic activation of `ollama.service` on Linux systems. 

Reason for this request is to conserve system resources, avoiding running unnecessary services.

Currently, after every update, I need to manually run the command:

```bash
sudo systemctl disable --now ollama.service
```
Is there a possibility to introduce a feature that makes this behavior configurable? 🛠️

Three practical solutions to control the automatic activation of `ollama.service` could be:
- Ask the user if he/she wants to activate the service [here](https://github.com/jmorganca/ollama/blob/main/scripts/install.sh#L113)
- Command-Line Flags: 
such as --disable-auto-service or --no-service. Users can run Ollama with this flag to prevent the automatic activation of the service. 
- Disabled by Default, Enable with Installation Flag: 
Make `ollama.service` disabled by default. During installation or setup, provide an option like --enable-service to allow users to explicitly enable the service if they want it.

**Comment by oliverbob** [comment]
I second the motion.

**Comment by computersrmyfriends** [comment]
+1

**Comment by maxtheaxe** [comment]
would like this as well

**Comment by jmorganca** [comment]
Hi all, for this you can use a drop-in file:

```
[Service]
ExecStart=
```

See https://www.flatcar.org/docs/latest/setup/systemd/drop-in-units/ for example

**Comment by Samk13** [comment]
@jmorganca Thanks for the feedback, 
However, you didn't provide a realistic alternative solution like having a flag to disable auto service run during the installation, such as e.g.: 
`curl -fsSL https://ollama.com/install.sh | sh -- --services-off`. 
Using `systemd` drop-in units is an option, yes, but it might not be user-friendly for everyone. 
```bash
# Create a drop-in file and add content to disable the service
sudo mkdir -p /etc/systemd/system/ollama.service.d && echo -e "[Service]\nExecStart=" | sudo tee /etc/systemd/system/ollama.service.d/override.conf
# Reload the systemd daemon
sudo systemctl daemon-reload

```
The suggested solution is not ideal, as I will not make this change just for installing Ollama. 
Relying on users' laziness to keep it running in the background is not a good idea to me, especially from a reputable company like yours!

Please reconsider other alternatives as this pushes users away from installing Ollama and limits user adoption.

**Comment by damien-git** [comment]
I had 3 services instead of ollama.service: `snap-ollama-19.mount`, `snap-ollama-27.mount` and `snap.ollama.listener.service`. Sorry, no time for this madness. Uninstalling it was my best option.

**Comment by slyyyle** [comment]
@Samk13 Respectfully, this is cognitive dissonance.

Ollama is poorly implemented.  I know this because I generated a more useful model managing wrapper through qwen in 5 minutes.

The issue people have here is not user laziness.  That is incredibly myopic.

My issue is no clear direction on the interaction between ollama.service, ollama serve, ollama run, and being able to expose it perpetually to an endpoint.  This is not farfetched corner case.  At the end of the day, Ollama is a glorified model manager.  With many backends available now, I see no reason not to see a wrapper.  the CLI and service interaction on linux, the complaints of automatic startup decoupled from ollama serve (why bind the service to the address and port I need if I can't api call it without contorting the api general form/routing to fit whatever this nebulous intended implementation was.

**Comment by native-apps** [comment]
Total regrets for installing this app.

**Comment by shvedes** [comment]
> Total regrets for installing this app.

Doesn't help with the issue. Stop trash talking
