### ISSUE TITLE
Update Script and Documentation for non-systemd Linux systems

### ISSUE THREAD

**Issue by NikeshKhatiwada** [ollama/ollama#1437]
I tried default installation script in Alpine Linux (WSL) and though it was apparently installed, I couldn't use ollama command. Also, manual install guide needs alternative steps for non-systemd sytems.

**Comment by jart** [comment]
The ollama binary needs glibc. This makes me sad, because I wanted to try it!

**Comment by NikeshKhatiwada** [comment]
I was able to use `ollama serve` command, which seemingly work; after manually installing **Ollama** following beginning of manual install guide, performing basic configuration in Alpine system, and then installing gcompat compatibilty layer. While trying `ollama run {model}`, it is able to download models but unable to run them showing following error:
`Error: llama runner process has terminated`

**Comment by dhiltgen** [comment]
@NikeshKhatiwada unfortunately I think you're going to be fighting an uphill battle to try to get all our dependencies working without glibc.   I would encourage you to try to build the source tree from main, since we've revamped a lot of the build process since you tried.  Maybe you can get it to build for CPU only mode.

**Comment by dhiltgen** [comment]
Our pre-compiled binary wont be viable for a non-glibc system.  I think we'd be open to community PRs to the build scripts if they're not complicated to enable building from source on a non-glibc system, but I'm going to close this ticket for now as I don't think it's something we plan to work on at this time.
