### ISSUE TITLE
`ollama list` syntax error

### ISSUE THREAD

**Issue by NILICK** [ollama/ollama#1466]
I installed ollama locally and it works successfully. I used multiple models such as `llama2` and `mistral`. I want to list models name using: 
`ollama list`

But it return:
```
/usr/bin/ollama: line 2: syntax error near unexpected token `<
/usr/bin/ollama: line 2: `<html><head>'
```

context of above path ollama file is:

```
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/download/ollama-linux-amd64</code> from this server.</h2>
<h2></h2>
</body></html>
```
How can I use `ollama list` command?

**Comment by mxyng** [comment]
It looks like your install was not successful since it didn't download ollama correctly. Does your network use a proxy?

**Comment by mxyng** [comment]
ollama itself doesn't seem like it's installed correctly. The binary `/usr/bin/ollama` should be an executable between 300-500MB in size. It shouldn't be an HTML file. 

Can you recount your installation steps? Ensure the proxy is configured correctly in the terminal session otherwise, it won't be able to reach out to download the ollama binary.

**Comment by pdevine** [comment]
Going to go ahead and close this. @NILICK unfortunately you'll need to re-install Ollama. Feel free to reopen if you're still having the problem.
