### ISSUE TITLE
Adjust Time for Ollama Serve to Stop Llama Runner Service

### ISSUE THREAD

**Issue by gzuuus** [ollama/ollama#1521]
Currently, the time it takes for Ollama Serve to stop the Llama Runner service is too short. It would be great to set the time to take longer to send the kill signal and stop the Llama Runner. Maybe its possible to add a configuration option to set the time it takes for Ollama Serve to stop the Llama Runner service.

**Comment by rgaidot** [comment]
Yes, knowing that the server llama.cpp (example in their repo.) in permanent execution and much faster, no re-runs, etc.. 

I also understand why ollama wants to turn it off. In my opinion, because I haven't gone through all the code, if users want to switch models and ollama is using server from llama.cpp with the old versions, you need to launch another server specifying the model for the `/completion` endpoint.

FYI, I'm using server from llama.cpp with their new endpoint (`/v1/chat/completions`).

Best.

**Comment by transcriptionstream** [comment]
I'm after similar, but opposite. The llama runner is holding gpu memory long after an api generate request is made. I'd love a way to adjust or stop the runners via api.
