### ISSUE TITLE
[Feature Request] Add Discussion Tab to Ollama Repo

### ISSUE THREAD

**Issue by scpedicini** [ollama/ollama#1532]
There's a lot of useful content in the Discord Ollama that is hard to search/organize. Given that the relatively large Ollama discord only has one channel `general`  - requests for help/etc can get lost pretty easily. 

@jmorganca I think it would be worth adding the Discussions Tab to the Github

![CleanShot 2023-12-14 at 17 32 03@2x](https://github.com/jmorganca/ollama/assets/2040540/0d2758cd-384c-467d-89e3-016b19a682a8)

**Comment by pdevine** [comment]
Hey @scpedicini , sorry about the slow response.

We've added a #help channel on the discord, and there is now a pretty vibrant community on [Reddit](https://reddit.com/r/ollama). I'm wary of adding Discussions just given how tiny the team is and it's already hard to sift through the number of issues (which is why it took so long to respond!)

I'm going to go ahead and close out the issue, but we may revisit it in the future if it seems appropriate.

**Comment by scpedicini** [comment]
@pdevine That's fair if you feel like Discussions would create more overhead to the team. I'm not a huge Reddit fan after what happened with the API pricing changes / etc. but I'll check out the new #help channel on Discord. Thanks!
