### ISSUE TITLE
Error while running ollama locally.

### ISSUE THREAD

**Issue by nehalmathew1996** [ollama/ollama#1579]
ConnectionError: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002298AE1EF50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by duhow** [comment]
Maybe this can help?

https://github.com/jmorganca/ollama/blob/86b0dd4b165497e08ec331e3c2c2aa229beb09db/docs/faq.md#how-can-i-expose-ollama-on-my-network

**Comment by technovangelist** [comment]
@nehalmathew1996 can you tell us more about what you are trying to do?

**Comment by Hidayathamir** [comment]
## Get Started

1. Run the Ollama Docker container:

```shell
sudo docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
```

For more detailed information, refer to the [Ollama Quickstart Docker](https://hub.docker.com/r/ollama/ollama). Please note we are using CPU only, the AI will response slow, if you have GPU, you can follow the instruction to run the docker and using your GPU to improve performance.

2. Pull the llama2 model:

```shell
curl --location 'http://localhost:11434/api/pull' \
--header 'Content-Type: application/json' \
--data '{
    "name": "llama2:7b"
}'
```

3. Chat with llama2

````shell
curl --location 'http://localhost:11434/api/chat' \
--header 'Content-Type: application/json' \
--data '{
    "model": "llama2:7b",
    "messages": [
        {
            "role": "user",
            "content": "why sky blue"
        }
    ]
}'```
````

**Comment by shreyasd2301** [comment]
> ConnectionError: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002298AE1EF50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

what was the issue?

**Comment by dhiltgen** [comment]
@nehalmathew1996 are you still having problems?  Can you upgrade to 0.1.22 and see if that resolves you problem?

**Comment by dhiltgen** [comment]
If you're still having problems with 0.1.22 or newer, please re-open.

**Comment by yixian3500** [comment]
I have a same problem, used with docker, sometime is happened with this:
[ollama] Connection Error, HTTPConnectionPool(host='172.17.0.1', port=11434): Read timed out. (read timeout=60)

my ollama version is 0.1.28

**Comment by imen-ben-atig** [comment]
same problem here

**Comment by dhiltgen** [comment]
@yixian3500 @imen-ben-atig Ollama is a client-server architecture, and this error is the client failing to connect to the server.  The underlying problem is likely a crash or hang in the server, and most likely your problems are unrelated to whatever was going wrong in Dec 18th when this issue was opened.  Please go ahead and file new issues for your individual connection problem and please include the server.log so we can investigate.

See https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md for guidance on how to find your server log.

**Comment by mlatti** [comment]
Install ollama on your system.
This may not cover all of the occurences, but if you're like me just getting started with llm's and your 101 tutorial doesn't mention this, you need to download and install ollama

**Comment by thepyper** [comment]
Ok, I think I've solved that in my setup, let's see if that's useful to anybody else...

My setup is:
1) Windows 10, where I installed ollama (with OllamaSetup.exe)
2) WSL + Ubuntu, where I installed OpenDevin

Actually the issue is made of the following issues:
1) You need to check that ollama is actually running, so try in windows 10 (ms-dos prompt or powershell)
curl 127.0.0.1:11434
You should get a "ollama is running" message
2) You need to understand that WSL is like a virtual machine, then "127.0.0.1" inside WSL does NOT mean connecting to windows 10, but connecting into the virtual environment in WSL.
3) You need to figure out the actual IP of the windows 10 machine seen from WSL. 
I did it with a "traceroute www.google.com" command, it gave me the following:
```
traceroute to www.google.com (142.250.180.132), 30 hops max, 60 byte packets
 1  DESKTOP-K5HF2NK.mshome.net (172.19.80.1)  0.315 ms  0.230 ms  0.207 ms
... more stuff...
```
So my windows 10 is seen from WSL + Ubuntu as 172.19.80.1.
So, my config.toml file in OpenDevin looks like:
```
LLM_MODEL="ollama/llama2"
LLM_API_KEY="na"
LLM_BASE_URL="http://172.19.80.1:11434"
LLM_EMBEDDING_MODEL="llama2"
WORKSPACE_DIR="./workspace"
```
4) Still things does not work, because by default ollama is only accepting local network connections.
So, you need to add an environment variable:
OLLAMA_HOST="0.0.0.0"
in your windows 10.
You can test quickly that in PowerShell, just quit ollama then open PowerShell and give:
```
$env:OLLAMA_HOST="0.0.0.0"
ollama serve
```
5) Now opening "localhost:3001" in browser (in windows 10) should give you a working OpenDevin.
At least mine is doing something with ollama, I can see in the console but I'm still waiting my response to "hello" :)

Hope this helps....

**Comment by mzeeshanarshad** [comment]
Anyone still having this error should try increasing the time out.

**Comment by wybaby** [comment]
1. set the URL be "http://host.docker.internal:11434" or your IP, instead of 127.0.0.1 or localhost. 
2. add an enviroment variable OLLAMA_HOST="0.0.0.0" (for Windows).

**Comment by cadubarbosabr** [comment]
Had the same issue.

Instead of using 
base_url: str = "http://**localhost**:11434"):
Try
base_url: str = "http://**127.0.0.1**:11434"):
