### ISSUE TITLE
Fails to load larger models, weight not found

### ISSUE THREAD

**Issue by spikespaz** [ollama/ollama#1667]
```
Linux odyssey 6.6.6 #1-NixOS SMP PREEMPT_DYNAMIC Mon Dec 11 09:40:17 UTC 2023 x86_64 GNU/Linux
```

I have attempted to run: `dolphin-mixtral`, `mixtral:8x7b`, `jmorgan/mixtral`, `mistral`, `llama2`.

`mistral` and `llama2` work fine, but the others all fail with the same error message:

```
error loading model: create_tensor: tensor 'blk.0.ffn_gate.weight' not found llama_load_model_from_file: failed to load model
```

The full output is included as a file.

[ollama-log.txt](https://github.com/jmorganca/ollama/files/13748283/ollama-log.txt)

**Comment by easp** [comment]
The nix package doesn't automatically require the right version of the llama.cpp package. Make sure that's at the right version #

**Comment by pdevine** [comment]
I think you were just running out of memory when you were trying to run the model. We've made several changes around how we handle memory since you filed this, so if you update to 0.1.28 and try again (depending on how much system memory you have, of course) it will probably work.

I'm going to go ahead and close out the issue, but feel free to keep commenting or reopen it if you have any questions.
