### ISSUE TITLE
is there a way to calculate token size?

### ISSUE THREAD

**Issue by ralyodio** [ollama/ollama#1716]
I don't know if this limitation exists with the api. I'm swtiching from openai to ollama api, and with openai I need to calculate token size and subtract it from the total 4096.

Do we need to do that for ollama api? If so, how do I caclulate token size of prompt?

**Comment by technovangelist** [comment]
Hi thanks for submitting the issue. Ollama doesn't require you to provide a number representing the quantity of tokens to the api. That said each model has a different context size and once you go over that, answers can degrade. Some models have a context size of 4k but 16k and 32k are showing up too. There are also some with 100k but they will require a huge amount of ram to run. 

Does this answer your question?

**Comment by ralyodio** [comment]
yes, thank you.

**Comment by mbrochh** [comment]
If I may add to this question:

What is the correct way to count the number of tokens when I build my prompt?

When interfacing with OpenAI, I can use the Tiktoken library, but I wonder if that library is also relevant when dealing with all other models that ollama supports?

**Comment by pamelafox** [comment]
I also have this question, as we have logic that tries to truncate conversation history to fit inside a context window and relies on the tiktoken encoding for the GPT models. I see some discussion about hugging face tokenizers but havent seen how easy they are to use. Curious for any packages that help with it, so that we can swap in ollama models easily.

**Comment by pamelafox** [comment]
Update: I found an approach here: 
https://github.com/simonw/ttok/issues/8
So I would need to map the model names here to the model names on HuggingFace in the Python in order to download the appropriate tokenizer.json. I'll try it out if I get a chance!

**Comment by gjke** [comment]
> Update: I found an approach here: [simonw/ttok#8](https://github.com/simonw/ttok/issues/8) So I would need to map the model names here to the model names on HuggingFace in the Python in order to download the appropriate tokenizer.json. I'll try it out if I get a chance!

This works if you know what your exact prompt is, which is the case in `generate` scenario.  However I was struggling to understand how to calculate the number of tokens in a `chat` scenario, where I have a list of messages. It turns out one can do:
```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("teknium/OpenHermes-2.5-Mistral-7B")
tokens = tokenizer.apply_chat_template(messages)
```
`len(tokens)` is what I was looking for. Maybe somebody will find this useful...

**Comment by mitar** [comment]
Where does ollama even tokenize? It does not use `transformers.AutoTokenizer` as it is Go code. And models in library also does not have a layer to tell which tokenizer to use? So how does ollama know for different models which tokenizers to use? Does tokenization happen at ollama level or somewhere else?

We would also like to know what is the input number of tokens and it would be great if ollama showed that in stats/responses.

**Comment by sc-govsin** [comment]
@gjke do you know whats the difference between ollama token count and Huggigface token count? I tested the following and token counts are never same 
```
llms = Ollama(model=model)
tokenizer = AutoTokenizer.from_pretrained(model_id_,)
token =tokenizer.encode(document)
if len(token)!=llms.get_num_tokens(document):
        print("Token from huggingface and Ollama are not same.")
```

**Comment by mitar** [comment]
Where is `get_num_tokens` defined?

**Comment by sc-govsin** [comment]
@mitar its a predefined method provided with langchain
https://api.python.langchain.com/en/latest/llms/langchain_community.llms.ollama.Ollama.html

**Comment by mitar** [comment]
To me it looks like an issue with langchain implementation, where `get_num_tokens` is not really defined for their `Ollama` class and just calls into [some default](https://github.com/langchain-ai/langchain/blob/9111d3a6369da71eb4c78d69bb20d20d00475d9a/libs/core/langchain_core/language_models/base.py#L41-L51).

**Comment by ralyodio** [comment]
can we get a javascript function to calculate token size? I need it for inputs and outputs to do some cost analysis on comparing groq.com api to renting my own gpu on tensordock.com

**Comment by chigkim** [comment]
Llama.cpp server has POST /tokenize and POST /detokenize.
Can we have that exposed to Ollama?
Then we can just count the number of tokens after tokenize.

**Comment by chigkim** [comment]
@jmorganca could you exposed these api points to Ollama?
Llama.cpp server has POST /tokenize and POST /detokenize.
https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md
Then we can just count the number of tokens after tokenize?

**Comment by davidearlyoung** [comment]
I 2nd this feature/ability to be implemented into Ollama.

I was in a situation recently where I really needed to know if a system prompt and prompt where getting close to a input context budget limit for a task. I was hoping that there was something to keep things simple, accurate and efficient and already built into ollama. My research yesterday on this lead me to discover that this is not the case. So I was a bit frustrated at the time that I have to wait, or that I currently would have to apply odd methods.
This concept is already built into, and is a useful feature from the core system that ollama is based on, llama.cpp. And I was a surprised that this was not already built into ollama to be honest.

At the moment, I don't have a lot to offer other then encouragement for those working on this. I'm glad that someone is looking into this.

**Comment by PyroGenesis** [comment]
For reference, FastChat provides the `/token_check` endpoint:

### Example:
#### Request body:
```json
{
  "prompts": [
    {
      "model": "llama3_large_cl",
      "prompt": "hello",
      "max_tokens": 0
    }
  ]
}
```

#### Response body:
```json
{
  "prompts": [
    {
      "fits": true,
      "tokenCount": 2,
      "contextLength": 262144
    }
  ]
}
```

The `tokenCount` is very useful, but I find the `contextLength` pretty useful too because it allows me to dynamically shorten my prompt until it meets the limit, rather than use a fixed limit.

**Comment by InAnYan** [comment]
Want to add my 2 cents here.

Knowing token count is very important in context of writing correct and general algorithms that split text and work with LLMs.

IMHO tokenization is really part of the domain of LLMs, and they shouldn't be separated. And I really like your approach to add new API endpoints for that. It would also easier to write algorithms, if OpenAI API also provided a token estimation endpoint.

On the other hand, it would be too expensive for big companies like OpenAI or Mistral to provide API for tokenization, because it could be done locally and it will only eat internet resources of those compaines.

So, if you develop an app that uses LLMs, and you want your app to support all kinds of LLM provides (or local LLMs), then you have to:
- For OpenAI or Mistral (or other big techs) - have a dedicated library for tokenization. OpenAI model count is stable more or less, changes are introduced slowly.
- For local models using ollama - ask the ollama about the token count, because a user may use dozens of different LLMs, and they all have their own tokenizers.

But, if both OpenAI and other providers also have a token estimation API endpoint, imagine how would be easier to write LLM apps with that: you just need a class like `OpenAiApiCompatibleChatLanguageModel` and that's it

**Comment by CharbelAD** [comment]
Any update on this issue? It would be extremely useful to have this feature implemented. Currently am using HuggingFace for the tokenizer and Ollama for inference.

**Comment by sc-govsin** [comment]
@CharbelAD there is a way to pass huggingface tokenizer as a parameter while making the llm object. I'll have to look into the code base again to share the code.

**Comment by CharbelAD** [comment]
> @CharbelAD there is a way to pass huggingface tokenizer as a parameter while making the llm object. I'll have to look into the code base again to share the code.

Thanks! No need to trouble yourself though, my current is just fine for the time being, but it would be more convenient to have everything in Ollama directly.

**Comment by jmorganca** [comment]
Thanks for the issue! Merging with https://github.com/ollama/ollama/issues/3582

**Comment by EthanRyne** [comment]
> [@gjke](https://github.com/gjke) do you know whats the difference between ollama token count and Huggigface token count? I tested the following and token counts are never same
> 
> ```
> llms = Ollama(model=model)
> tokenizer = AutoTokenizer.from_pretrained(model_id_,)
> token =tokenizer.encode(document)
> if len(token)!=llms.get_num_tokens(document):
>         print("Token from huggingface and Ollama are not same.")
> ```

thats because you need to convert it to `tokenizer.apply_chat_template()` instead of direct encoding, since chat template also adds all the relevant special tokens at every user and assistant turn before converting it into a single string of the entire conversation whereas just enocode only adds special token in the beginning or may be not even that, in general the special token insertion is different in the final chat template tokens which is passed to the model during inference
