### ISSUE TITLE
How to enable Ollama read contents of directory?

### ISSUE THREAD

**Issue by oliverbob** [ollama/ollama#1721]
Since it can read '/home/user/whateverfile.it.is', would it be possible for ollama to be able to read an entire directory or 'repo' for that matter so we can talk to it?

If it is not yet a feature, maybe its neat to add this for developers to help us quickly solve our coding challenges.

Thanks.

**Comment by technovangelist** [comment]
Hi @oliverbob , thanks for submitting this issue. To read files in to a prompt, you have a few options. First, you can use the features of your shell to pipe in the contents of a file. To read in more than a single file, you need to do a few extra steps because the contents of your files is probably bigger than the context size of the model. So you can use a technique known as RAG. We have a few examples here in our repo that show you how to do RAG with Ollama. Essentially, it comes down to importing your content into some sort of data store, usually in a special format that is semantically searchable. Then you filter the content based on a query. Then that is fed to the model with the prompt and the model generates an answer. The third option is to let someone else build RAG for your. On the front Readme of this repo is a list of community projects. Some of those do various forms of RAG on your files. 

Let me know if that answers your questions.

**Comment by jmorganca** [comment]
Hi @oliverbob this isn't something Ollama supports today. There are some open issues for having built-in vector store sort of functionality so I'll merge it with that #834
