### ISSUE TITLE
Scope of Ollama, 

### ISSUE THREAD

**Issue by Luxadevi** [ollama/ollama#1738]
Could you tell me more about the scope of Ollama,  you guys build it around the llama.cpp stack and added an API and other tools on top of that.

GGUF is pretty stable  but there are some other formats on the horizon. 
I would like to add EXL2 formatting to my app but since this is a companion app for ollama I was actually questioning where to add this functionality. It would be pretty easy to just add support for it on my end with some local code. 

But to be honest, I wouldn't mind building this within Ollama. P

So my question is would you be interested if I added transformers/c-transformers to Ollama. 

I'm very interested in your answer and what your long term goals would be for Ollama.

Happy holidays!

**Comment by pdevine** [comment]
@Luxadevi thanks for your comment!

We currently build around llama.cpp, but the intention has always been to have a simple API for users to be able to run inference, along with making it really easy to find and download models. We chose llama.cpp because it gave us a great starting point for doing that. The intention has never been to only support GGUF.

That said, we're pretty conscientious about not bloating the project with too many features, or support too many things. It's easy to add stuff which doesn't get enough attention and drags down the overall quality of everything.

**Comment by pdevine** [comment]
Going to go ahead and close the issue.

**Comment by houmie** [comment]
@pdevine  Sorry, I found this by Googling. Does Ollama support exl2 or no?

**Comment by pdevine** [comment]
@houmie Not currently.

**Comment by txhno** [comment]
@pdevine will ollama be getting exl2 support in the future?

**Comment by pdevine** [comment]
@txhno do you mean as an on-disk format or for importing weights? As an on-disk format it would be unlikely, however, I could see us supporting importing exl2 weights in the future. We do support importing some models from safetensors now (i.e. Huggingface format) including llama, mistral, gemma, and phi.
