### ISSUE TITLE
[FEATURE] add more options while chatting like `/bye` (e.g `/clear_context` or `/new_chat`)

### ISSUE THREAD

**Issue by tikendraw** [ollama/ollama#1751]
While chatting with the model, you necessarily do not need to have the context, or you just want a new chat. Well,  there are no options for this, rather than just cancelling this chat and restarting it.

So, similar to the `/bye` option, there can be other options for the ease of using llm.
* `/clear_context` or `/no_context`: to not use the above context
*  `/new_chat` : to initialize new chat

or any other option that may be useful for the user.

**Comment by rgaidot** [comment]
Maybe it's up to front to manage the context? Otherwise sessions will have to be introduced? No?

**Comment by rgaidot** [comment]
So currently, I don't think it's up to Ollama to make this secret sauce.

**Comment by tikendraw** [comment]
Generally, this LLM apis has a memory or context as  argument in order to continue the chat; just not passing previous data will work for clear context.

**Comment by FlippingBinary** [comment]
> Generally, these LLM apis has a memory or context as argument in order to continue the chat; just not passing previous data will work for clear context.

How would one do that in the CLI? Right now, I exit with `/bye` then manually delete the history file (`~/.ollama/history`), then load the model again. It would be quite nice if there was a command to clear the context, like `/reset` or `/new_chat` or anything would be nice.

**Comment by pdevine** [comment]
@FlippingBinary If you just want the history to not be updated you can use the `/set nohistory` command. I actually have a change to clear the context as well, but I'm still not super happy with it. I'll be taking a look at this this coming week though.

**Comment by FlippingBinary** [comment]
@pdevine Thank you for the tip. I just tested that feature a bit more and now realize that I conflated context and history. Now I know that I have no use for history, but there doesn't seem to be a persistent way to disable it. I tried `ln -s /dev/null ~/.ollama/history` but ollama just deleted the symbolic link and recreated the text file during the next session. There appears to be no way to prevent it from being created and growing because it somewhat ironically records the `/set nohistory` command in the history so the history file grows with duplicate lines of `/set nohistory` if you run that command at the start of each session. 

It would be nice to have a persistent `nohistory` setting or even a command-line argument, but I suppose that's not all that important because it doesn't affect the context of future sessions. For resetting the context, closing the session with `/bye` and opening again works well enough for the time being.

**Comment by easp** [comment]
> IMO - So currently, I don't think it's up to Ollama to make this secret sauce.

@rgaidot OP seems to be talking about adding commands to the ollama CLI. This CLI is provided in this repo as part of the Ollama project. How is their request out-of-scope for the project?

**Comment by rgaidot** [comment]
> @FlippingBinary If you just want the history to not be updated you can use the `/set nohistory` command. I actually have a change to clear the context as well, but I'm still not super happy with it. I'll be taking a look at this this coming week though.

At first, I thought it was for API (not CLI), hence my first reply

**Comment by rgaidot** [comment]
@easp At first, I thought it was for API (not CLI), hence my first reply

**Comment by pdevine** [comment]
With `0.1.21` you'll be able to type `/load <model>` which will clear your context. You can also use `/save <model>` which will save your conversation up until that point and you can reload it later.

I _think_ that meets the spirit of this issue, so I'm going to go ahead a close it. Please feel free to reopen!

**Comment by FlippingBinary** [comment]
The new `/load <model>` command works well! Perhaps now it would be possible to make `/load` with no parameter have the effect of `/load <model>` where `<model>` is the name of the most recently loaded model? I think that would fully meet the spirit of this issue.
