### ISSUE TITLE
 I have a problem I get many #

### ISSUE THREAD

**Issue by necro304** [ollama/ollama#1762]
![image](https://github.com/jmorganca/ollama/assets/31376673/7b4f060d-22a1-4992-9251-b479c0178779)

**Comment by pdevine** [comment]
@necro304 Does this happen with all models, or only llama2? What are the specs for you machine, what version of ollama are you running (use `ollama --version`), and what version of llama2 are you using (`ollama list | grep llama2`).

**Comment by necro304** [comment]
ollama version is 0.1.17

llama2:latest   78e26419b446    3.8 GB  11 hours ago

**Comment by igorschlum** [comment]
Hi @necro304 This issue seems to be similare to this issue: https://github.com/jmorganca/ollama/issues/969
Can you confirm? If yes, add a comment to issue 969 and close this one. it seems to be a memory error on your GPU or CPU. Could you give more details in issue 969 of your hardware configuration?

**Comment by pdevine** [comment]
I believe this ended up being fixed a while ago. The most recent version of ollama is 0.1.28. The llama2 model that you have should still be the latest. I'm going to go ahead and close out the issue, but feel free to reopen it if you're still having the problem.
