### ISSUE TITLE
Pulled SQLCoder2 even though it's not listed in the library

### ISSUE THREAD

**Issue by lestan** [ollama/ollama#1820]
I wanted to test out sqlcoder2, but only saw sqlcoder on the [model library page](https://ollama.ai/library?sort=newest&q=llama)

I still tried to see what would happen if I ran Ollama pull sqlcoder2...and it worked

It pulled down the model named sqlcoder2:latest 

Is this an issue with the model library not being up to date or is it downloading sqlcoder (assuming v1) even though I'm asking for sqlcoder2.

Here's the output of the modelfile

```
lestan@Lestans-MacBook-Pro learn-text-to-sql % ollama show sqlcoder2 --modelfile 
# Modelfile generated by "ollama show"
# To build a new Modelfile based on this one, replace the FROM line with:
# FROM sqlcoder2:latest

FROM /Users/lestan/.ollama/models/blobs/sha256:4018b30faaf8b1e4cedad4dff4871f74e369950ddd25a0a4e8b0657a18710517
TEMPLATE """{{ .Prompt }}"""
PARAMETER stop "<|endoftext|>"
```

**Comment by igorschlum** [comment]
Hi @lestan 

SQLcoder2 seams to be a valid model. It's bigger than SQLCoder (9 GB instead of 4.1).

It could be a copy of sqlcoder:15b what has the same size.

Ollama pull sqlcoder2
pulling manifest 
pulling 4018b30faaf8... 100% ▕████████████████▏ 9.0 GB                         
pulling a67353d85e36... 100% ▕████████████████▏  21 KB                         
pulling 1576480a555b... 100% ▕████████████████▏   36 B                         
pulling 1cc25ac1ef96... 100% ▕████████████████▏  386 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
success 
(base) igor@Mac-Studio-192 ~ % ollama show sqlcoder2 --modelfile 
# Modelfile generated by "ollama show"
# To build a new Modelfile based on this one, replace the FROM line with:
# FROM sqlcoder2:latest

FROM /Users/igor/.ollama/models/blobs/sha256:4018b30faaf8b1e4cedad4dff4871f74e369950ddd25a0a4e8b0657a18710517
TEMPLATE """{{ .Prompt }}"""
PARAMETER stop "<|endoftext|>"
(base) igor@Mac-Studio-192 ~ % ollama run sqlcoder2
>>> give me the sql to delete a database

# drop database <database-name>;

>>> Send a message (/? for help)

**Comment by pdevine** [comment]
We had set `sqlcoder2` to be hidden while we were testing it, and then forgot to delete it. You should just use the `sqlcoder` model as it should be the most up-to-date. I've gone ahead and removed `sqlcoder2` from the registry so you won't be able to pull it any more.

Thanks for the issue!
