### ISSUE TITLE
Consult where Ollama models are saved in Linux.( in WSL on windows)

### ISSUE THREAD

**Issue by zephirusgit** [ollama/ollama#1836]
Hello, I'm really running Ollama, in WSL Windows Subsystem Linux, (in Windows) Now, my problem is that when you lower a new model, call2, llava, or create some, these models are downloaded, or copied, in some folder , I imagine the WSL? De Linux? or Windows?
For example, I wanted to run the mixtral model, which occupies 26gb
And where I have it, I "double it" and I do not.
  Does anyone know where those files can be putting?
From already thank you very much,
In Windows I walk very well call2 and llava, (describing images)
compared to another llava that ran before which I required 3 simultaneous processes that occupied me as 90gb of RAM

enfin any tip is appreciated, to find them,
I saw that if I believe them, and then I eliminate them, they are erased, but as I have very little disk space, I want to see how I can use them, without being doubled,
I think I move it to another album and install it, from there, so as not to run out of space, I already have very little, greetings!
​

**Comment by EmmaWebGH** [comment]
I would like to add to this, is there a way we can point to a common repo on our HDD/SSD? Rather than have every LLM app download it's own copy of the model, and have 5x Mistrals on disk?

And yes, when a model is auto-downloaded, where does it go please?

**Comment by dcasota** [comment]
@zephirusgit fyi

1. Description
  The declarative description of a llm is stored in `~/.ollama/models/manifests/registry.ollama.ai/library`. 
  ![image](https://github.com/jmorganca/ollama/assets/14890243/804b2bb5-770d-4406-bb18-e232ca62de3e)
  These are cached local files. Your download from registry.ollama.ai afaik isn't accountable. As long as Ollama.ai maintain their free of charge service, you can reload a llm.  If you are sure, delete the local cached library subdirectories e.g. 
    ```
    cd ~/.ollama/models/manifests/registry.ollama.ai/library
    rm -r  -f llama-pro
    ```
   The local cached sha files (digest, partial or full) are stored in `~/.ollama/models/blobs`.
   If you are sure, delete those files, too.

2. In wsl2, the underlying virtual machine diskfile can be compacted.
  1. Start a Windows Terminal (Administrator)
  2. Run `wsl --shutdown`
  3. Double check where the ext4.vhdx file is stored e.g. "c:\users\yourusername\ext4.vhdx".
  4. Start `diskpart`
    4.1 `select vdisk file="c:\users\yourusername\ext4.vhdx"`
    4.2. compact vdisk
    4.3. exit
  5. Close Powershell Terminal (Administrator)

In windows file explorer you can check the right-sized ext4.vhdx file.

In comparison, Ollama in a VMware By Broadcom Workstation guest Linux os, if you are sure, you can make use of the built-in gui function "Compact".

  ![image](https://github.com/jmorganca/ollama/assets/14890243/4a9cf25c-62c2-469c-aa7a-1c3614bf1d45)

**Comment by EmmaWebGH** [comment]
I found my models are going into 
\\wsl.localhost\Ubuntu\usr\share\ollama\.ollama\models

And the FAQ says we can move this folder with a change to an environment variable.

BUT
What are these blobs?

The models I want to run, I have already downloaded. I've tried a lot of LLM apps, and the models are named like so:
`model.safetensors`
In a folder with the name of the model:
`models\TheBloke_Orca-2-13B-GPTQ`
And some JSONs for settings.

How do I get Ollama to use that model? Seems like I can't simply point it to that models folder because Ollama is expecting:
`sha2568934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246`
??

**Comment by zephirusgit** [comment]
thanks i find it on 

C:\Users\*****\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu_79*****gsc\LocalState\ext4.vhdx

I did not know what that virtual unit could be compressed! But layers is a good idea, it occupies 66gbs now, I have it in a very fast M2 so it is almost instantaneous everything, I wanted It detects Nvidia, and it doesn't work, but maybe you can copy that ext4.VHDX file, and see if it works by replacing it?

**Comment by EmmaWebGH** [comment]
I found my models are going into
\wsl.localhost\Ubuntu\usr\share\ollama.ollama\models

And the FAQ says we can move this folder with a change to an environment variable.

BUT
What are these blobs?

The models I want to run, I have already downloaded. I've tried a lot of LLM apps, and the models are named like so:
model.safetensors
In a folder with the name of the model:
models\TheBloke_Orca-2-13B-GPTQ
And some JSONs for settings.

How do I get Ollama to use that model? Seems like I can't simply point it to that models folder because Ollama is expecting:
sha2568934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246
??

**Comment by zephirusgit** [comment]
I have caused several LLMS, although Ollama is the one that is faster, I was using Zephyr (Zephyr-7b-Bet Although I still don't try to create it inside Ollama, then I tell you, I think I will have to remove the mix, and try, because I have no space anymore.

**Comment by dcasota** [comment]
@zephirusgit The library functionality and userfriendly consumerization of LLMs are Ollama strengths. Basically this has nothing to do with a model development and maintenance.
Integrating Zephyr, I guess https://github.com/jmorganca/ollama/blob/main/docs/import.md is the lookup docs.

You're right. The ext4.vhdx location depends on the configured WSL2 "virtual unit". Yes, this "virtual unit" aka virtual machine instance can be compacted to save more space on your computer. But, compacting/compressing is not deduplication. This imples a storage server functionality. Universities I know typically use VMware datacenter solutions and benefit from [VSAN deduplication](https://docs.vmware.com/en/VMware-vSphere/8.0/vsan-administration/GUID-3D2D80CC-444E-454E-9B8B-25C3F620EFED.html).

@EmmaWebGH I do not know the Ollama architecture. Your question might be answered by @jmorganca?
The userfriendly LLM naming is stored in the library, and the manifest file holds all sort of digit sums for the large blob files per LLM. Afaik all models must be in the same computer folder. The FAQ do not mention a distributing storage locations possibility.

**Comment by EmmaWebGH** [comment]
@dcasota appreciate you're trying to be helpful, I was assuming the devs check these issues once in a while. If you're not a dev no need to answer that you don't know. But thanks.

**Comment by pdevine** [comment]
Sorry for the slow response guys. There's actually an [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-set-them-to-a-different-location) which explains how to do this. *The short answer* is use the `OLLAMA_MODELS` environment variable if you want to put the models in a different location.

One big caveat here is that Windows and Linux use different file names for the blobs because NTFS doesn't support `:` in a file name. We've been talking about changing Linux to use the same file names though to make this cross-platform compatible in the future, but no timeframe for that right now.

I'm going to go ahead and close the issue, but feel free to keep commenting.
