### ISSUE TITLE
Models not listed after installing nvdia drivers and CUDA

### ISSUE THREAD

**Issue by PriyaranjanMaratheDish** [ollama/ollama#1962]
1)I had copied models (blobs and manifests) from my mac to /usr/share/ollama/.ollama/models/manifests folder.
2)I was able to see them when I ran ollama list.
3)I then installed nvdia drivers and CUDA. 
4)Now I am not able to see the models. 

ollama list models shows the following 
NAME    ID      SIZE    MODIFIED

5)How to fix this issue?

**Comment by oliverbob** [comment]
I'm not sure if Linux is the same on Mac running Ollama. But I tried this on Ubuntu. I had to be certain that I have copied the files as root and everything worked fine.

After doing the copy, I have to ensure that permission was set for all files and directories and subs:

`chown -R user:user /usr/share/ollama/` because when you copy as root, the directories are owned by root:root.

**Comment by dhiltgen** [comment]
@PriyaranjanMaratheDish I would tend to agree this sounds like it may be a permission problem of not setting ownership to the `ollama` user/group.  If you're still having problems with this, please share a little more information.  `sudo ls -lR /usr/share/ollama/.ollama/models` and also share the server log so we can see what happens at startup.
