### ISSUE TITLE
Feature request - support symlink to GGUF in custom model instead of GGUF 1:1 copy

### ISSUE THREAD

**Issue by mirekjany** [ollama/ollama#1981]
Hello there,

maybe I'm missing something from the documentation. I am working with lots of custom models where the only difference is in System prompts but the custom models are always based on the same GGUF file. So, having ollama to always copy/duplicate it again and again when I create new model is

1) time-consuming
2) eats disk-space very quickly

Now, after model is created, I delete the duplicate blob and manually symlink it to the source GGUF, which is a little bit inconvenient.

Would it be possible to implement this? Something like a parameter called SYMLINK (besides FROM).

Thanks!

**Comment by easp** [comment]
You only need to specify the GGUF once, for the first model you create. Any time you create a new model, reference that model by name, rather than the location of the GGUF.

For example, say you first `ollama create my-base ...`. If you want to create another model based on the same GGUF, use `FROM my-base`, not the path to the GGUF.

Beyond that, Ollama tracks the uploaded weights using a hash of the actual data. If you upload the same file twice, they'll have the same hash and so only a single copy of the data will be stored.

**Comment by pdevine** [comment]
@mirekjany as @easp was saying, Ollama does de-duplication automatically for any layer. If a layer is the same between models, only one copy will be saved. It does this using content addressability; the layers are stored by their sha256 hashes in the `models/blobs/` directory, and the manifest for the model always references the data by that hash.

**Comment by mirekjany** [comment]
Appreciate the clarification, works as expected, closing the issue.

**Comment by mirekjany** [comment]
Appreciate the clarification, works as expected, closing the issue.
