### ISSUE TITLE
"Illegal Hardware Instruction" on fresh install

### ISSUE THREAD

**Issue by yourfavoritedev** [ollama/ollama#2035]
**Steps to reproduce**

- I followed the download instructions on the README for MacOS. Unzipped the file and opened the GUI. Successfully downloaded.
- Opened iTerm and tried to run `ollama run zephyr`

Got this error:

<img width="497" alt="image" src="https://github.com/jmorganca/ollama/assets/28208066/1adc46f1-6297-4566-9c2f-b87776a7a4e4">

Hardware:
Macbook M1 Pro 2021
16 GB

**Comment by igorschlum** [comment]
Hi @yourfavoritedev I have a Macbook Pro 2011 M1pro with 32GB and it works.
what version of MacOS have you?
Try to restart and launch Ollama again to see if you have still the same issue.
There is this issue that says, that it could be a new problem on the 0.1.20
https://github.com/jmorganca/ollama/issues/1938
try to download the 0.1.19 version to see is the issue was already there.
Version 0.1.19 for macOS can be downloaded here.
https://github.com/jmorganca/ollama/releases/download/v0.1.19/Ollama-darwin.zip
Tell us if it works.
Best

**Comment by jmorganca** [comment]
Hi @yourfavoritedev , I'm sorry you're getting this error. Would it be possible to run the following in your terminal?

```
sysctl -n sysctl.proc_translated
```

If the result is `1`, it may be that your terminal/shell was started in x64 mode (for Intel) using Rosetta.

**Comment by igorschlum** [comment]
Hi @yourfavoritedev I went in the Utilities folder on MacOS, I displayed the Get Info window on Terminal, I checked "Open with Rosetta", and Could reproduce the issue. So just uncheck "Open with Rosetta" in the finder and try again and it will works. It's no more possible to duplicate the Terminal App, having one running on Rosetta and the other one running as M1 Pro. Thank you @jmorganca

**Comment by amanreddy77** [comment]
> * `ollama run zephyr`
same issue
how to resolve

**Comment by dhiltgen** [comment]
We've added support for x86 CPUs without vector extensions (AVX, AVX2) which now means ollama can run under rosetta.  You'll still get the best performance running native ARM on an ARM Mac though.
