### ISSUE TITLE
Minimal use of GPU in Docker (windows) with 10/33 layers loaded

### ISSUE THREAD

**Issue by sumitsodhi88** [ollama/ollama#2038]
my GPU is being used 23% while cpu is at 100% while using a docker image in windows environment.

**Comment by easp** [comment]
Your GPU is waiting for your CPU, which is the result of the model not fitting in VRAM.

**Comment by dhiltgen** [comment]
@sumitsodhi88 if you're still having this problem, can you share the server log?

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues

**Comment by dhiltgen** [comment]
```
2024-01-27 07:12:33 llm_load_tensors: offloaded 10/33 layers to GPU
```

So roughly 1/3 of the model is loaded into GPU, and the remaining 2/3's is on your CPU, and I/O bandwidth between the two can have a significant performance impact.  You can try to use a smaller model to try to get more (or ideally all) of it to fit in VRAM on your GPU, or try forcing CPU only and see if running CPU only is actually faster since it cuts out the I/O between system memory and the GPU.

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#llm-libraries

**Comment by remy415** [comment]
@sumitsodhi88 1050 with 2gb vram isn't going to do LLM serving very well. You'll need a model smaller than 2GB or it won't load all the layers into the GPU. The reason it isn't using all of the vram is likely because of a fixed batch size -- loading another batch would bring the vram use above the available size. 

You may want to consider a new system, or try running AVX2 on CPU. It won't be as fast as GPU acceleration, but it'll run faster than base CPU.

**Comment by dhiltgen** [comment]
@sumitsodhi88 we've been adjusting our memory prediction calculations quite a bit over the past few weeks, and while they're still not perfect, we're aiming to get relatively close to saturating the GPU VRAM without overshooting and causing OOMs.  My suspicion on differing behavior between local and container is you're probably running different versions of the server in each.  Make sure to `docker pull ollama/ollama` to get the latest image, and check the server logs near the beginning to confirm both your host and container are running the same version.   If they're still radically different in the number of layers loaded, please share the two logs so we can see more details.

**Comment by pdevine** [comment]
Unfortunately with a 2GB video card there are diminishing returns as to which layers can be offloaded reliably onto the GPU.

I'm going to go ahead and close this for now. I think ollama _is_ getting better at being able to place different layers on the GPU, but beyond a certain point it's difficult to eek out performance on older/low performance cards.
