### ISSUE TITLE
Questions about context size

### ISSUE THREAD

**Issue by swip3798** [ollama/ollama#2204]
Before I start, thank you for this amazing project! It's really great to run LLMs on my own hardware this easily.

I am currently building a small story writing application that uses ollama to have a "cowriter" AI, that will write along with the user, similar to how AIDungeon or NovelAI work. Since the stories have no limit in size, they will eventually become large than the context size of the model. This now has led me to multiple questions on how exactly ollama handles cases, where the prompt is larger than the context size of the chosen model. Will it get trimmed, and if yes how exactly? Is the template always in the context and just the prompt trimmed, or will it be cut off too? Or do I understand this completely wrong?

Additionally the users of my app should be able to add a "long term memory", essentially just more text that will be put at the beginning of the prompt, so that the AI can have info of the story that is already outside of the context size. That of course makes it necessary, that this memory text will definitely be in the context of the model.

Now, all of this would be fairly simple to implement myself, if there would be a tokenize/detokenize endpoint. I have seen the issues regarding that, so maybe this can also be achieved using the chat endpoint? But then again, what happens when the context size is exceeded?

Sorry for all those questions at once, I would be really thankful, if you could share some insights on how this works.

**Comment by Jurik-001** [comment]
Exact following question i also asked myself: "This now has led me to multiple questions on how exactly ollama handles cases, where the prompt is larger than the context size of the chosen model. Will it get trimmed, and if yes how exactly?"

**Comment by swip3798** [comment]
I also found #1963, there seems to be a pull request already related to trimming the prompt for the chat endpoint. If I understand this correctly, it would make sure that the template and system message is preserved completely.

**Comment by jukofyork** [comment]
Yeah, I've just been thinking about this too as I'm sending large amounts of code and can quickly approach the 16k context window.

It would be nice to have a clear understanding of exactly how the chat completion API will handle this.

For my use case I'd most like to keep the system prompt and then do a "First In, Last Out" removal of the oldest messages (or user assistant message tuples for the chat completion API) so as to never go over the context limit.

Just having an API endpoint to count the tokens would be enough for me to do this myself (actually just found somebody mentioned in the request thread for this feature that you can get this from the  embedding API call by counting the number of items returned!?).

**Comment by jmorganca** [comment]
The context limit defaults to 2048, it can be made larger with the `num_ctx` parameter in the API. However for large amounts of data, folks often use a workflow called RAG to store data outside of the context window and bring in chunks where required. Hope this helps!

**Comment by nikhil-swamix** [comment]
cant i do ?
`ollama setdefault num_ctx=8192` or similar?
lacking this critical feature. i have to create a proxy so model does not re init with requests of different num_ctx?
im getting migrane as i see models loading and unloading as i make http requests. please suggest best method.
@jmorganca

**Comment by nikhil-swamix** [comment]
> The context limit defaults to 2048, it can be made larger with the `num_ctx` parameter in the API. However for large amounts of data, folks often use a workflow called RAG to store data outside of the context window and bring in chunks where required. Hope this helps!

this is not true, chunking RAG is bad or in other words, atleast 500 tokens fetched for top 3 results would be 75% of 2048, and leaves with mere 500 tokens to work with. and folks using ollama usually know hardware reqs, especially on production they get bigger machines for safety and accomodate Compute and memory. an article axplains this
![image](https://github.com/user-attachments/assets/285d006b-7264-4be7-a349-e733c2dab9cf)


as @homjay pointed, people are ever hungry for longer context as they compensate for finetuning and increase relevance, as big as 2048 may sound, its actually numbers from 2022... and most settings are preferred on server side/one time setup rather than API calls. on a side note, i would like to raise a PR which allows enhanced env settings which allow to configure defaults for a model tag `ollama setenv <TAG> num_ctx <VALUE>` as there are other settings like GPU/Layer splitting which do the same API based and leads to reloading in most cases. 
please guide me @jmorganca , im not a go lang expert, but will try my best.

**Comment by qiulang** [comment]
"However for large amounts of data, folks often use a workflow called RAG to store data outside of the context window and bring in chunks where required. " I don't think this is the case. 

The chunk data RAG retrieves is put in prompt, which takes up the context window.
