### ISSUE TITLE
Nvidia Tesla M60

### ISSUE THREAD

**Issue by nejib1** [ollama/ollama#2250]
Hello,

I would like to inquire whether the Nvidia Tesla M60 is compatible with Ollama's code. 
Can someone please provide information or insights regarding this compatibility?

Thank you!

**Comment by easp** [comment]
That Compute Capability of that card is 5.2.  Support for 5.2 was just merged this past weekend and so I'd expect it to show up in the next release. I'd guess that would happen in the next week or two.

**Comment by lirc572** [comment]
Hi @nejib1, have you tested it out? I am considering getting a M40 or M60 card if it is significantly faster than CPUs for running Ollama.

**Comment by orlyandico** [comment]
I went on an ancient GPU buying spree in 2022 and ended up with a K80 and M60.  The K80 isn't great because it's compute capability 3.7 (only recently working, but you have to build ollama from source). The M60 is newer, but is in many ways weaker than the K80 (only 1 GPU, and only 8GB RAM).

The king of cut-rate GPU's right now has got to be the P40, which you can get on ebay for $200. It's a bit faster than an Nvidia T4 or RTX 3060, but the killer is it has 24GB RAM.  It doesn't support float16 however (rather, it does, but is immensely slow) so any code that can leverage float16 or Tensor cores would be much faster on a more modern GPU.  But at a cost less than a 3060...

**Comment by lirc572** [comment]
@orlyandico Very informative. Thank you!!

I have a 16GB 4060Ti (around $600) on my PC. It's imo the best modern Nvidia GPU with enough VRAM and an okay-ish performance for people on a budget.

I want to build a cheap always-on server that can run some LLM workloads. The P40 looks like a great option. My only other concern is its power consumption... If it's gonna add $50 to my monthly electricity bill, I would rather get another 4060Ti.

**Comment by nejib1** [comment]
> Hi @nejib1, have you tested it out? I am considering getting a M40 or M60 card if it is significantly faster than CPUs for running Ollama.

Hello, 
I bought a new one RTX A4000, it's  a bad idea to work with old GPU..

**Comment by bmizerany** [comment]
Nvidia Tesla M60 should be supported in the current release of Ollama. Closing this, but please reopen and post server logs `~/.ollama/logs` if you have issues.
