### ISSUE TITLE
When I run a local model, GPU is used, but the CPU is 100%

### ISSUE THREAD

**Issue by thugbobby** [ollama/ollama#2270]
When I run a local model, GPU is used, but the CPU is 100%, and it will be crashed.
![image](https://github.com/ollama/ollama/assets/68416779/2dc6dbf4-b786-4250-9996-20915a5b5ee5)
![image](https://github.com/ollama/ollama/assets/68416779/89c31672-2d47-4cd1-ad34-9e47fb2063af)

**Comment by mehdiataei** [comment]
Same issue. GPU is not used at all (the memory is allocated though)

**Comment by ltomes** [comment]
This has been brought up on this ticket as well: https://github.com/ollama/ollama/issues/1663
I have similar symptoms but using an A5000.

**Comment by penouc** [comment]
This seems to be a new version issue. I tried using ollma0.1.20 and found that the CPU's percentage could go over 100%, without crashing.
![image](https://github.com/ollama/ollama/assets/1774022/6e03b496-786c-45f1-8919-215579fc6039)

**Comment by easp** [comment]
What model are you using?

**Comment by thugbobby** [comment]
> What model are you using?

yi:34b-chat

**Comment by dhiltgen** [comment]
@thugbobby from your screenshot, it looks like python is using up most of your VRAM, leaving ollama with very little to fit in, so that implies it's loading only a small number of layers into the GPUs, and most of the work is being done by the CPU.   Either load Ollama before your python app, or somehow configure python to use less VRAM, and you should get more layers loaded into the GPU.  While we probably could load a few more layers from the looks of things, we try to be a little conservative in our memory prediction calculations, and we're continuing to refine those.

If you're still having problems, please share your server log and I'll re-open the issue.
