### ISSUE TITLE
Slow response with concurrent requests

### ISSUE THREAD

**Issue by oxaronick** [ollama/ollama#2282]
Ollama is great. It makes deploying LLMs easy. However, I have an issue with sending two requests to Ollama within a second or so of each other.

When I do this, Ollama usually responds to one of the requests fine, but the CPU usage jumps by at least 100% and the other request doesn't get a response. Sometimes it will after many minutes, but I don't always wait around to find out. Responses are normally returned within 2s of a request.

I'm running Ollama on an A100 with 80GB of VRAM and according to `nvidia-smi` Ollama is only using ~7GB.

I would expect it to handle one request, then handle the other, both on the GPU but I'm wondering if the second request is causing Ollama to try to run something on the CPU.

How can I configure Ollama to handle concurrent (or near-concurrent) requests better?

**Comment by rcgtnick** [comment]
Thanks, @nathanpbell, that's helpful.

> As to why it's running the second request on CPU - are you requesting the same model for each? If you are (it's not unloading one model to load the next model), then there may be a bug there.

I was sending concurrent requests for different models. I'll try with just a single model.

**Comment by rcgtnick** [comment]
I haven't been able to reproduce with one model, but using a single instance of Ollama for chat and code completion causes the issue pretty reliably for me.

Is there a way to disable CPU processing? I can find docs on disabling GPU but not CPU. Even if one client got an error message instead of a response it would be preferable to having Ollama leave requests hanging until it's restarted.

**Comment by rcgtnick** [comment]
I have 80GB of VRAM, with over 70GB free. I'm not even sure it's trying to run on the CPU, I just see the CPU usage spike.

**Comment by bmizerany** [comment]
Closing as dup of #358
