### ISSUE TITLE
36GB Macbook not using GPU for models that could fit

### ISSUE THREAD

**Issue by WinnieP** [ollama/ollama#2370]
https://github.com/ollama/ollama/blob/27aa2d4a194c6daeafbd00391f475628deccce72/gpu/gpu_darwin.go#L24C1-L28C3

In older versions of Ollama, certain models would run on the GPU of a 36GB M3 macbook pro (specifically q4_K_M quantization of mixtral). Now, it's running on CPU.
I believe MacOS is allowing closer to ~75% of the memory to be allocated to GPU on this model, not 66%.

```ggml_metal_init: recommendedMaxWorkingSetSize  = 28991.03 MB```

**Comment by padok** [comment]
I have a similar experience with my 32GB M1 Pro Macbook.

Previously, I was able to use the following model (or its similar sized predecessor) on the GPU:
```
dolphin-mixtral:latest        cfada4ba31c7            26 GB
```
Even though it took some time to load and macOS had to swap out nearly everything else in memory, it ran smoothly and quickly.

However, now that the model is being run on the CPU, the speed has significantly decreased, with performance dropping from 3-6 words/s to just ~0.25 words/s, making it unusable for me.

Given that I was able to run models of this size before, I would argue that even utilizing around 81% of the available memory (~26GB) may be possible.

---

I cannot remember making any changes to the memory limit using the command:
```
sudo sysctl iogpu.wired_limit_mb=
```
so this could potentially be a behavior specific to my system, rather than a general problem. But it worked!

**Comment by thony-p** [comment]
I use this [patch](https://github.com/ollama/ollama/pull/2354) so ollama won't ignore:
Thanks to @peanut255
```shell
sudo sysctl iogpu.wired_limit_mb=26624
```
It would be great if it were merged soon.

**Comment by peanut256** [comment]
#2354 now solves you issue without having to set iogpu.wired_limit_mb (if you system has enough available VRAM by default)

**Comment by dhiltgen** [comment]
It looks like we can mark this closed.  If you're still seeing it run on CPU mistakenly, let us know and I'll re-open.

**Comment by chigkim** [comment]
@dhiltgen I'm not sure if this is the same issue, but I'm running Ollama 0.1.31 on MBP 16" m3 64GB running Sonoma 144.4.1.

I imported [miqu-1-70b.q5_K_M.gguf](https://huggingface.co/miqudev/miqu-1-70b/blob/main/miqu-1-70b.q5_K_M.gguf) which is 48.8GB.

When I use the model with api, my memory usage only jumps from 6GB to 16GB, and cached file indicates 49GB.

Why does it run from cache even though it has enough memory to load the entire model?
