### ISSUE TITLE
unable to initialize llm library Radeon card detected

### ISSUE THREAD

**Issue by sigmaya** [ollama/ollama#2392]
Hello,
I am trying to run as user and manually, i get this error:
time=2024-02-07T19:00:18.967+01:00 level=INFO source=payload_common.go:106 msg="Extracting dynamic libraries..."
Error: unable to initialize llm library Radeon card detected, but permissions not set up properly.  Either run ollama as root, or add you user account to the render group.

I had a firepro w7100 but some days ago , i removed it and now i am using an nvidia 3060, I am on ubuntu 20 and i have no idea how to tell ollama that the gpu is nvidia.

**Comment by sigmaya** [comment]
I had to remove amdgpu mod .

**Comment by unclemcz** [comment]
@swoh816 you can try:
1. sudo systemctl stop ollama
2. sudo ollama serve

**Comment by swoh816** [comment]
@unclemcz Thanks, you're right, I used `sudo` and it doesn't raise an issue with amdgpu anymore.

Btw, may I ask why is that the case? Ollama used to work without root permission until recently, so it puzzles me that it suddenly dooesn't work without the root permission.

Also, is Ollama incompatible with AMDGPU and that's why you cannot initialize with Radeon card?

**Comment by unclemcz** [comment]
@swoh816 actually,i don't know either,just follow the error info and  keep trying again and again. o(╥﹏╥)o

**Comment by swoh816** [comment]
@unclemcz You actually helped me work, thanks :) I was trying to get Obsidian Copilot work, and you gave me a huge hint to come up with a solution: https://github.com/logancyang/obsidian-copilot/issues/269#issuecomment-1969011057
