### ISSUE TITLE
Offline models are not appearing on the Ollama server list

### ISSUE THREAD

**Issue by HariKunapareddy** [ollama/ollama#2421]
**Problem**
 I download model on the the machine where Ollama installed and  have internet access. Then moved the model files from the folder usr/share/ollama/.ollama/models to the new machine which doesn’t have internet access. I could see Ollama is not detecting those models and they are not visible as part of list command. 
 
**Expected**

Ollama list 

should list the new models files transferred.

**Comment by jithinmukundan** [comment]
Could you find any resolution? I am facing the same issue. Tried all possible changes related to permissions, systemd file etc. No luck yet.

**Comment by GanizaniSitara** [comment]
Need solution too. On windows moved both the BLOB content and the library subfolders. No cigar.

**Comment by GanizaniSitara** [comment]
PS: what really sucks it succeeds with 

"ollama cp my_invisble_model my_invisible_model2"

It creates the new folder and copies the manifest, but still doesn't list the model and when you try to run it insists on connecting to the internet. There must be somewhere else it looks?

**Comment by pdevine** [comment]
Hey guys, sorry for the slow response.

If you are moving between Windows and Linux, the problem is the filenames of the blobs in linux look like `sha256:<sha256 hash>` whereas NTFS doesn't support a `:` in the file name. Unfortunately you have to rename the files.

For moving files to a different place, you should be able to use the `OLLAMA_MODELS` environment variable when you're starting Ollama. There is an [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored) which covers how to use that.

**Comment by GanizaniSitara** [comment]
Hi Patrick, thank you, that's helpful  for cross-platform moves. I've resolved mine from going windows to windows and making sure I copied all dependencies.

**Comment by HariKunapareddy** [comment]
Thanks! this solved the issue.
