### ISSUE TITLE
Error: unable to initialize llm library Radeon card detected, but permissions not set up properly.  Either run ollama as root, or add you user account to the render group.

### ISSUE THREAD

**Issue by pladaria** [ollama/ollama#2442]
I'm unable to run ollama. My setup:

* OS: Linux
* CPU+GPU: AMD Ryzen 3 2200G with Radeon Vega Graphics
* GPU: nVidia Tesla P40 - 24GB RAM

```
$ ollama serve
time=2024-02-10T12:21:38.851+01:00 level=INFO source=images.go:863 msg="total blobs: 0"
time=2024-02-10T12:21:38.851+01:00 level=INFO source=images.go:870 msg="total unused blobs removed: 0"
time=2024-02-10T12:21:38.851+01:00 level=INFO source=routes.go:999 msg="Listening on 127.0.0.1:11434 (version 0.1.24)"
time=2024-02-10T12:21:38.851+01:00 level=INFO source=payload_common.go:106 msg="Extracting dynamic libraries..."
Error: unable to initialize llm library Radeon card detected, but permissions not set up properly.  Either run ollama as root, or add you user account to the render group.
```

Same result using `sudo` or adding myself to the `render` group.

Also tried:

`OLLAMA_LLM_LIBRARY="cuda_v11" ollama serve`
`OLLAMA_LLM_LIBRARY="cpu_avx2" ollama serve`

with the same results

**Comment by user414** [comment]
We are having the same issue, except that it works for us with sudo but the problems is it requires sudo and stores models under root instead of the current user.  We have not investigated yet but it seems an issue when doing a manual install perhaps there's some hard coded user group, maybe the ollama user and group indicated in the script install.

**Comment by unclemcz** [comment]
https://github.com/ollama/ollama/issues/2392#issuecomment-1968245555

**Comment by user414** [comment]
We had similar issue, except that adding to the render group work. Please note that on linux for the groups changes to take full effect you have to logout and login again or reboot the system. If adding users to a group is not possible for whatever reasons changing the udev permission is also an option see here

https://github.com/ROCm/ROCm/issues/1798#issuecomment-1849112550

During our investigation we realized that this was caused by not being able to read the /dev/kfd. We also found that some people did not have this file, which is strange. This did not happen to us but it could be due to a very old kernel, somewhere around 2014 seem to be the first kfd commit in the kernel, or perhaps a moded amdgpu driver.

Also note to get amd gpu acceleration one need to have the ROCM framework, which is the AMD equivalent of the CUDA framework for Nvidia, installed. Here are instructions for Ubuntu and Ubuntu derivative

https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/native-install/ubuntu.html

**Comment by pladaria** [comment]
I want to use the nVidia card, not the AMD one

**Comment by dhiltgen** [comment]
@pladaria we don't currently optimize for hybrid setups with mixed vendor GPUs.

That said, you're in luck, in that we do try nvidia first, and if that works, we use it without proceeding to the AMD GPU.  You will need to add the ollama user to the render group to get past the amd gpu permission check we run at startup, but after that, it should use your nvidia card.  If that's not working, please run the server with OLLAMA_DEBUG=1 and share the server log so we can understand why it's not working properly.
