### ISSUE TITLE
Error: listen tcp 127.0.0.1:11434 in windows

### ISSUE THREAD

**Issue by razvanab** [ollama/ollama#2540]
I get this error in Windows  ollama preview when I try to run "ollama serve."

Error: listen tcp 127.0.0.1:11434: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by razvanab** [comment]
Ok, I think I got it.
Ollama is already running in the background as a server in Windows at: http://localhost:11434.
Just put that address in your browser, and you'll see

**Comment by fdzl22** [comment]
Thanks,brother

**Comment by Zxyy-mo** [comment]
Thanks,brother

**Comment by JerryOver** [comment]
I got this problem. How do you exit Ollama?

**Comment by JerryOver** [comment]
So I exited Ollama from the taskbar, and "http://localhost:11434/" was no longer reachable with the message: "Ollama is running". So it's off. Then I opened it with my command prompt with "C:\Users\hinso>ollama serve", and I got this output: 

time=2024-04-05T07:13:53.844-05:00 level=INFO source=images.go:804 msg="total blobs: 6"
time=2024-04-05T07:13:53.851-05:00 level=INFO source=images.go:811 msg="total unused blobs removed: 0"
time=2024-04-05T07:13:53.852-05:00 level=INFO source=routes.go:1118 msg="Listening on 127.0.0.1:11434 (version 0.1.30)"
time=2024-04-05T07:13:53.881-05:00 level=INFO source=payload_common.go:113 msg="Extracting dynamic libraries to C:\\Users\\hinso\\AppData\\Local\\Temp\\ollama1623166627\\runners ..."
time=2024-04-05T07:13:54.024-05:00 level=INFO source=payload_common.go:140 msg="Dynamic LLM libraries [cpu_avx cpu rocm_v5.7 cpu_avx2 cuda_v11.3]"
[GIN] 2024/04/05 - 07:14:08 | 200 |            0s |       127.0.0.1 | GET      "/"

I checked the taskbar. Ollama isn't open there, but "http://localhost:11434/" is available again saying, "Ollama is running". I just want to get back to where I was chatting with it in my command prompt. I can't seem to get back there. I closed the command prompt because I thought that I could reopen it without a model loaded. I was trying to install something for Comyui.
