### ISSUE TITLE
Slow download speed on windows

### ISSUE THREAD

**Issue by bcllcc** [ollama/ollama#2613]
![1708430844061](https://github.com/ollama/ollama/assets/73450286/ba92400e-d3bc-4a94-8e5b-50fbc53199ab)

**Comment by EmmaWebGH** [comment]
Same issue? Or different
https://github.com/ollama/ollama/issues/2850
Can't DL a single thing. Strangely llama2 worked when I first set up the Win version. Now... nothing. It either sits at 0 bytes, or something dumb like 8 bytes/ sec, or cancels itself with an error.

**Comment by hoyyeva** [comment]
Hi @bcllcc & @ewebgh33, really sorry for the trouble. It seems this issue is quite similar to what we've seen in #2850, so I'm going to merge them to keep our discussions streamlined. If you believe there's something unique about this issue that needs separate attention, please don't hesitate to reopen it. Thanks for your understanding.
