### ISSUE TITLE
How to update all models

### ISSUE THREAD

**Issue by misaligar** [ollama/ollama#2633]
Do I have tun run `ollama pull <model name>` for each model downloaded? Is there a more automatic way to update all models at once?

**Comment by seanmavley** [comment]
That'll be a nice feature, but as it stands now, shouldn't be hard to do yourself with a single command like below

```
ollama list | awk 'NR>1 {print $1}' | xargs -I {} sh -c 'echo "Updating model: {}"; ollama pull {}; echo "--"' && echo "All models updated."
```

**Comment by Natfan** [comment]
Here's a little PowerShell script to do the same thing, if you're on Windows or have it installed on your OS. Note that you may need to update the URI if you're hosting on a different port/server (I personally am using an NGINX reverse proxy)

`(Invoke-RestMethod http://localhost:11434/api/tags).Models.Name.ForEach{ ollama pull $_ }`

To perform a dry-run of the command, simply add quotes around "ollama pull $_" to print the command to the terminal instead of executing it.

**Comment by hoyyeva** [comment]
Hi @misaligar, it looks like this issue is quite similar to what's been reported in #2586. We understand the current workaround isn't ideal, but please know we're actively seeking a more effective solution. We'll keep the community updated as soon as we make progress that improves the situation. For now, I'll close this issue, but we're aware of this issue and working to resolve this.

**Comment by TadayukiOkada** [comment]
hope this will be merged soon:
https://github.com/ollama/ollama/pull/2179

**Comment by sammcj** [comment]
I have a little zsh alias that adds this functionality you might find useful:

```bash
# wrap the ollama command, if the parameter is pull with no other parameters pull all models
function ollama() {
  if [[ $1 == "pull" ]] && [[ $# -eq 1 ]]; then
    echo "pulling all models..."
    ollama list | awk '$1 !~ /^registry.local/ {print $1}' | while read -r model; do
      echo "Pulling $model"
      ollama pull "$model"
    done
  else
    command ollama "$@"
  fi
}
```

**Comment by cycleuser** [comment]
On Windows, PowerShell users can use this:

`$models = ollama list | Select-Object -Skip 1 | ForEach-Object { $_.Split()[0] }
foreach ($model in $models) {
    Write-Output "Updating model: $model"
    ollama pull $model
    Write-Output "--"
}
Write-Output "All models updated."`

**Comment by misaligar** [comment]
> On Windows, PowerShell users can use this:
> 
> ```powershell
> $models = ollama list | Select-Object -Skip 1 | ForEach-Object { $_.Split()[0] }
> foreach ($model in $models) {
>     Write-Output "Updating model: $model"
>     ollama pull $model
>     Write-Output "--"
> }
> Write-Output "All models updated."
> ```

Thank you! That didn't work for me and I came up with the following:

```powershell
function updateModels {
    $models = ollama list | Select-Object -Skip 1 | ForEach-Object {
        if ($_ -notmatch '^NAME\s+') {
            if ($_ -match '(\S+)\s+') {
                $Matches[1]
            }
        }
    }

    if ($models.Count -eq 0) {
        Write-Output "No models found to update."
        return
    }

    foreach ($model in $models) {
        Write-Output "Updating model: $model"
        ollama pull $model
        Write-Output "--"
    }
    Write-Output "All models updated."
}
```

**Comment by obk** [comment]
ollama list | tail -n +2 | awk '{print $1}' | xargs -I {} ollama pull {}
