### ISSUE TITLE
Download Monitoring Error

### ISSUE THREAD

**Issue by crimson206** [ollama/ollama#2651]
![Screenshot 2024-02-21 204740](https://github.com/ollama/ollama/assets/110409356/70962ea7-5ae7-4cf1-bb64-7b6a76ee1ce9)

**Comment by mxyng** [comment]
Are you capturing stderr to a file? 

The output is intended to be written to a terminal and uses ANSI escape characters to rewrite the screen. Writing those characters to a file has no effect and you get the screenshot as a result.

There's no great alternative other than not writing ANSI escape characters when not in terminal mode. This has side effects such as writing new lines for each screen update which will output many extra lines.

My suggestion here will be to redirect stderr to /dev/null since it doesn't seem like you're interested in pull progress.

```
ollama pull llama2 2>/dev/null
```
