### ISSUE TITLE
Embedding usage without starting a server

### ISSUE THREAD

**Issue by linonetwo** [ollama/ollama#2704]
So we can use it in nodejs worker_thread without starting a server, and I/O with FFI instead!

**Comment by mitar** [comment]
I am not sure about using it from nodejs, but I am curious if there is an example how to use it from a Go program directly.

**Comment by netroy** [comment]
Ollama embeddings API is build on top of llama.cpp, [which now has node.js bindings](https://github.com/withcatai/node-llama-cpp). You can use these bindings to use create embeddings without Ollama (or any server).

**Comment by jmorganca** [comment]
Hi there, sorry this isn't possible today with Ollama. It's something we're thinking about making possible with the [Javascript](https://github.com/ollama/ollama-js) and [Python](https://github.com/ollama/ollama-python) libraries, but haven't started building that yet. Would it be possible to create an issue on that repo? Thanks so much

**Comment by mitar** [comment]
I would like to do it with Go. So I think this issue here should then be for tracking enabling Go embedding?

I was looking into this a bit and I think it could work with a bit of reorganizing, so that generate is called by Go to generate the .a file which then is should be found by a sub-package's `go:embed`.

**Comment by pushangupta** [comment]
Hi. Do you know if this is available? If we can use the embedding functions without a server that'd be great.
