### ISSUE TITLE
Set max output tokens with Ollama + Llama index

### ISSUE THREAD

**Issue by antoinelemor** [ollama/ollama#2717]
I'm trying to set an output max tokens with llama index but it doesn't work. Can someone help me? 

import pandas as pd
import os
from llama_index.llms.ollama import Ollama
from transformers import AutoTokenizer
from llama_index.core import Settings

Configure the settings for the LLM
Settings.llm = Ollama(model="mixtral:8x7b-instruct-v0.1-q5_K_M", max_tokens=5)

Initialize the Ollama model with the modified settings
llm = Settings.llm

**Comment by mxyng** [comment]
You might have better luck in the llama index [repo](https://github.com/run-llama/llama_index) since it looks like the main interface is `llama_index.llms.ollama.Ollama`.

Ollama supports limiting token output (and many other options) through the JSON field `options` in the generate or chat request, e.g. 

```
curl http://127.0.0.1:11434/api/generate -d '{"model":"mistral","prompt":"What is the meaning of life?","options":{"num_predict":10}}'
```

**Comment by Darthph0enix7** [comment]
You can just pass the num_predict to the ollama class:


```
from llama_index.llms.ollama import Ollama

Settings.llm = Ollama(model="llama3", request_timeout=100.0, additional_kwargs={"num_predict": 10})
resp = Settings.llm.complete("Who is nikola Tesla?")
print(resp)
```
