### ISSUE TITLE
Windows portable mode?

### ISSUE THREAD

**Issue by DartPower** [ollama/ollama#2734]
Can you do the portable mode? 
e.g. zipped variant of installed portable distro of ollama, because i'm have a very small free space on system disk but have external SSD for AI

**Comment by jmorganca** [comment]
Hi there, please see https://github.com/ollama/ollama/pull/2739 - this should lower the minimum space required on your system desk. Thanks so much for the issue!

**Comment by d416** [comment]
I second a .zipped portable executable here.  I'm in a corporate environment were we do not have local admin access and full installs are blocked. (Portable executables are ok (perhaps because they are pre-scanned and jailed locally).  

I can do the install.exe, but it's a support ticket for someone to remote in and do it for me which is inconvenient.  My name also is auto-added to an information security 'eyebrow raise' list where I wish it wasn't.

**Comment by muerzi** [comment]
portable version would be nice

**Comment by augus1990** [comment]
I have the same problem. A portable version would be useful.

**Comment by OfficiallyCrazy** [comment]
So this has been closed but i still don't understand how this is portable version.

**Comment by OfficiallyCrazy** [comment]
Th OP did not ask to resolve the issue of low space. He requested a ZIP portable version of Ollama. Something i can keep on my Pendrive.

**Comment by mlgitter** [comment]
I vote for the portable feature.

There should be 2 versions - one with folder selection (current doesn't allow for this) and one fully portable.
Users shouldn't be tied to a OS copy.

**Comment by 4156-tech** [comment]
yeah

**Comment by louia** [comment]
Any news on a portable version for windows ? Why this issue is closed ?

**Comment by Packsolite** [comment]
Maybe we should just create a new issue?
