### ISSUE TITLE
Support custom install dir in Windows installer

### ISSUE THREAD

**Issue by olexx** [ollama/ollama#2776]
Hi,
Is there an option to install the windows app NOT on C:\ drive ?

e.g.: E:\Program Files\.....

**Comment by eastsidejapan** [comment]
i would like to install this another drive also. dont have enough space on c:\
will instructions be added how to install to another drive? or option with the windows installer?

**Comment by dhiltgen** [comment]
We don't offer support for system service install today.  It always installs in your user home directly. After install, you can change where the models are stored by following the instructions here https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored

**Comment by agonzalezm** [comment]
can you add /silent mode to installer?  and also add install method using powershell with iwr to download the script like you do for linux/mac with curl ?

**Comment by nviraj** [comment]
I have found 2 working methods so far, documenting it in case it helps somebody. 

- Locate the file directory and move it to your desired location and add the new directory to your system path so that the Ollama executable can be found. 
- Use [winget](https://winget.run/) to install (One time) and update Ollama (Every time you need to update). Make sure you use the location flag for both commands. If not, the update will reset to the default location. 
  - `winget install -i -e --id Ollama.Ollama --location D:\Apps\Ollama`
  - `winget upgrade -i -e --id Ollama.Ollama --location D:\Apps\Ollama`

The second method is my preferred one. Please note that -i flag makes the installation interactive. Remove it for unattended installation.
