### ISSUE TITLE
Add/Remove Model Repos + Self Host Your Own Model Repo + Pull Models From Other Repos

### ISSUE THREAD

**Issue by trymeouteh** [ollama/ollama#2841]
1. The ability to manage the model repos in Ollama. Simular to how in F-Droid (Android app store) you can add and remove repos which allows you to get apps from other sources.

2. Self host your own repo. Allow anyone to self host their own repo.
- Weather this means simply setting up a git repo (Github, Gitlab, Gitea, Forgeo) or self hosting a website and server for hosting models.
- Models can be stored as direct downloads or torrents. Would like to see a torrent option to help reduce bandwidth on the repo provider and encourage users of the model to seed the model (sharing is caring)

3. The ability to pull models from other sources. If the same model is available on Ollama repo and on another repo, to have a way to download both or distinguish which model you want to download.

**Comment by pdevine** [comment]
1. You can do this by signing up for an account on ollama.com. Upload your Ollama public key and then you can push your own models.
2. This is also doable today using the docker registry, however, there are some breaking changes that are going to come for this over the next few months. Also, the way we handle auth is different than the way docker handles it (see the first comment about adding your public key)
3. This already works. Also, because we deduplicate the data, you only store one copy on disk.

I'm going to go ahead and close the issue, but feel free to keep commenting.

**Comment by snooze92** [comment]
I would really like a way to host an internal private repository for models, "on-prem", so that members of one private organisation can share models easily without leaking them out.

**Comment by xuxinping** [comment]
> 我真的很想找到一种方法来托管一个“on-prem”的模型内部私有存储库，这样一个私人组织的成员就可以轻松共享模型，而不会泄露它们。



> I would really like a way to host an internal private repository for models, "on-prem", so that members of one private organisation can share models easily without leaking them out.

The Folib artifact repository supports the management of over 20 types of language artifact repositories, including those for Maven, npm, Go, and Hugging Face. In the future, it will also support the private hosting of the Ollama model.
