### ISSUE TITLE
Kaspersky Internet Security detects false positive

### ISSUE THREAD

**Issue by yanniedog** [ollama/ollama#2855]
<img width="996" alt="image" src="https://github.com/ollama/ollama/assets/25560742/fd2921ef-908b-4ade-b633-df0da7c89585">

**Comment by yanniedog** [comment]
It detected a range of Ollama files. Here is the full list:

[ollama-kaspersky.txt](https://github.com/ollama/ollama/files/14456992/ollama-kaspersky.txt)

**Comment by amnweb** [comment]
Kaspersky and MS Defender are turning into the worst security apps ever seen. 
Try upload ext_server.dll and llama.dll on virus total or Kaspersky Threat Intelligence Portal and please share result so we can compare, because this two files from your list must be clean, there is some other reason why is detected as Trojan and and I'm afraid it isn't Go problem.

**Comment by dhiltgen** [comment]
Is anyone still seeing these false positive reports?

**Comment by yanniedog** [comment]
No, the virus reports I encountered in version version 0.1.27 seems to be
fixed in version 0.1.28

**Comment by jmorganca** [comment]
Will close as this seems to have subsided. Sorry about all the false positive warnings.
