### ISSUE TITLE
Windows install path

### ISSUE THREAD

**Issue by pozzo-balbi** [ollama/ollama#2938]
Hi,

please add an option to choose an installation path, e.g. c:\program files\ollama during install. Installing under the user's home directory is security wise a bad idea.

Thanks

**Comment by dhiltgen** [comment]
Installing outside of the users home directory would require elevated privileges, and we're aiming to install without admin.

We might consider adding an option to install as a system service in the future, however we do include the stand-alone windows executable in our releases, so it should be possible to "roll your own" system service.

**Comment by Ivanmatthew** [comment]
I think using symlinks for at least moving models to another station. Can somebody confirm?

**Comment by ayushchinmay** [comment]
I think it would be really useful to be able to migrate the application files, or at least the downloaded model files to a different location.
For the current release, is there any way to either download the model in a different drive, or move the entire application itself to another drive? I was able to achieve this through WSL.

**Comment by dhiltgen** [comment]
@ayushchinmay the model storage location can be changed via environment variable.  See https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored

**Comment by ayushchinmay** [comment]
That worked! Thank you so much, that saves my C: drive.

**Comment by dhiltgen** [comment]
Just noticed we have 2 issues tracking this.  Lets use #2776

**Comment by Leoleojames1** [comment]
Awesome, I tried to change my OLLAMA_MODEL env var and it failed, now after reverting to none. and even when defining the var OLLAMA_MODEL as C:\Users\ADA\.ollama\models\ the error code below persists,

I still receive this error no matter the combination:

C:\Users\ADA>ollama run C3PO
pulling manifest
Error: pull model manifest: file does not exist

**Comment by gabenitez** [comment]
you can also specify custom install dir using the /dir param, just install using command line interface:
```
ollamasetup.exe  /DIR="d:/ollama"
```
t

**Comment by leosamuele221** [comment]
> you can also specify custom install dir using the /dir param, just install using command line interface:
> 
> ```
> ollamasetup.exe  /DIR="d:/ollama"
> ```

This should be the final answer
Thanks!

**Comment by AK-1000** [comment]
> you can also specify custom install dir using the /dir param, just install using command line interface:
> 
> ```
> ollamasetup.exe  /DIR="d:/ollama"
> ```

You saved my life ! Straight to the point, thank you.

**Comment by thezolon** [comment]
> #### Add a comment
> Comment

It also won't take the CLI parameters in powershell I discovered. Works when I use cmd instead. At least this is how it behaves on my system. (Win11)

**Comment by SpoffNinja** [comment]
> > you can also specify custom install dir using the /dir param, just install using command line interface:
> > ```
> > ollamasetup.exe  /DIR="d:/ollama"
> > ```
> 
> This should be the final answer Thanks!

It's a great temp solution but should be no means be the "final answer". If you want better adoption in the space then they should just add a folder location browse button on the install splash screen where that can be set.

Also would be fantastic to have that custom install location info on the main github page than hidden away in the Issues comment section

**Comment by Septemberlemon** [comment]
> you can also specify custom install dir using the /dir param, just install using command line interface:
> 
> ```
> ollamasetup.exe  /DIR="d:/ollama"
> ```

That did work!Thank you.
But how did you find that?

**Comment by seoninja13** [comment]
> ollamasetup.exe  /DIR="d:/ollama"

You might have to use '.\ollamasetup.exe  /DIR="d:/ollama"', depending on from where you are runnign the command

**Comment by ferderer** [comment]
> you can also specify custom install dir using the /dir param, just install using command line interface:
> 
> ```
> ollamasetup.exe  /DIR="d:/ollama"
> ```

Isn't working, it still writes everything to AppData/local

**Comment by tushgaurav** [comment]
> > ollamasetup.exe  /DIR="d:/ollama"
> 
> You might have to use '.\ollamasetup.exe /DIR="d:/ollama"', depending on from where you are runnign the command

Thanks for this bro.

**Comment by allhailpython** [comment]
on windows 11 the command is:

Start-Process -FilePath "C:\Users\Max\Downloads\ollamasetup.exe" -ArgumentList "/DIR=`"C:\Program Files\ollama`"" -Verb RunAs -Wait

**Comment by lehenshtein** [comment]
> on windows 11 the command is:
> 
> Start-Process -FilePath "C:\Users\Max\Downloads\ollamasetup.exe" -ArgumentList "/DIR=`"C:\Program Files\ollama`"" -Verb RunAs -Wait

or just use cmd

**Comment by EvgeneKuklin** [comment]
Please, add folder choosing to UI, why should user google how to do the essential thing?

**Comment by ufenx** [comment]
> you can also specify custom install dir using the /dir param, just install using command line interface:
> 
> ```
> ollamasetup.exe  /DIR="d:/ollama"
> ```

Thanks. I've noticed someone saying that D: vol requires additional permission. Is it still an issue in practice?

**Comment by adamk33n3r** [comment]
> Installing outside of the users home directory would require elevated privileges

Not necessarily. You generally don't need elevated privileges to install to an extra drive/partition.

**Comment by chasanpro** [comment]
Start-Process -FilePath "Z:\Downloads\OllamaSetup.exe" -ArgumentList '/DIR="Z:\Ollama"'

This thing worked for me

**Comment by Aqua-Pulco** [comment]
yes it worked! Adding a folder location browse button would be great ! also

.\OllamaSetup.exe /DIR="D:\ollama"

**Comment by dori4n** [comment]
> Installing outside of the users home directory would require elevated privileges, [...]

I would like to chime in here and posit, that this is exactly what I would want. I would prefer all my executable to be installed to a location that requires elevation of granting ACL permissions as an elevated user, such that these files cannot be written to as an unprivileged user. Ideally, I would want that no executable can be run from a location other than such, but... sadly that's not possible.

The installer should provide the option to install for **All Users**, install to `%PROGRAMFILES%` and ask for elevation by default, and also have an install for **Only me** option that a user can select that installs to `%LOCALAPPDATA%\Programs\<program name>` by default, with both options allowing the user to change the installation path, if desired.

The automatic updater should then detect which installation method was previously chosen, ask for elevation if necessary and update the existing installation as a appropriate.

Offering to only install to the user's home directory has two obvious downsides:
1. On shared machines, this duplicates the installation into every user's home directory. At several gigabytes of space that adds up fast.
2. Any program the user runs can modify the files and use them as an entry point with which to launch other programs (like malware and spyware), which may be less than desirable. This issue is exacerbated, because Ollama becomes a resistent program in the system tray that enters itself into the autostart list by default.
