### ISSUE TITLE
OLLAMA_MODELS env variable in bashrc doesnt work

### ISSUE THREAD

**Issue by harsham05** [ollama/ollama#2940]
Ive added the following to my .bashrc but Ollama doesnt seem to storing them there.

`export OLLAMA_MODELS=/path/to/models/`

**Comment by easp** [comment]
What platform are you using? That's only going to work if you launch `ollama serve` from a bash shell. If you are using Mac, or Windows, or the service that's installed on linux you have to set the environment variables other ways:

https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server

**Comment by harsham05** [comment]
Im using Linux.

**Comment by bmizerany** [comment]
@harsham05 Would you please provide the output of `echo $OLLAMA_MODELS` from a fresh bash session?

**Comment by mxyng** [comment]
As @easp already mentioned, `OLLAMA_MODELS` must be set in the same context as `ollama serve`. Setting it in `.bashrc` is _probably_ not what you want _unless_ you're invoking `ollama serve` directly.

Since you're using Linux, is it possible there's an systemd ollama.service running? If so, you'll need to set `OLLAMA_MODELS` in the systemd service. [This](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-linux) section of the FAQ has the details.

**Comment by jmorganca** [comment]
Will close this for now, see @mxyng's answer for best practices currently

**Comment by Nilabb** [comment]
> Ive added the following to my .bashrc but Ollama doesnt seem to storing them there.
> 
> `export OLLAMA_MODELS=/path/to/models/`

If you look at the ollama daemon configuration file you might notice a few things.
```
ExecStart=/usr/bin/ollama serve
...
User=ollama
Group=ollama
```
This means when you start ollama you are executing `ollama serve` as the user ollama. Just as if you were to use `sudo -u ollama ollama serve`. So, if it's in your .bashrc and not ollama's, it probably can't recognise it. 
Also see https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server
