### ISSUE TITLE
Support "tool" role in messages

### ISSUE THREAD

**Issue by lebrunel** [ollama/ollama#3165]
### What are you trying to do?

The new Herme 2 Pro model recommends results from function calling to come in messages with the role "tool", eg:

```
<|im_start|>tool
<tool_response>...result here...</tool_response>
<|im_end|>
```

The chat api doesn't support messages with a role "tool" - treats it as a bad request.

### How should we solve this?

Accepting the "tool" role in messages API would make life easier for those using Hermes Pro - and any future models that are likely to be based off the same open data sets.

This has implications for how templating works in Ollama - it may even require a total rethink of templates.

### What is the impact of not solving this?

Not solving it means that users have to create their own templates and use Ollama's `raw` option, which negates some of the joy of using Ollama in the first place.

I truly believe function calling and building local agents is one area where Ollama really could excel, if the experience of doing so is made totally painless.

### Anything else?

Repo of Hermes Pro function calling with prompting/templating instructions:
https://github.com/NousResearch/Hermes-Function-Calling

**Comment by napa3um** [comment]
You will probably also need the assistant_tool_call role for support JSON-mode response:

```
<|im start|>assistant
<tool_call>...requested tools here...</tool_call>
<|im_end|>
```

**Comment by napa3um** [comment]
JSON-mode for `<|im_start|>assistant<tool_call>...` support is also needed.

**Comment by napa3um** [comment]
JSON-mode support for `<|im_start|>assistant<tool_call>...` is also needed.

**Comment by lalanikarim** [comment]
This is also needed for a cleaner implementation within langchain.
Currently [ChatOllama](https://python.langchain.com/v0.2/docs/integrations/chat/ollama/) [doesn't support handling `ToolMessage`](https://github.com/langchain-ai/langchain/blob/3d6e8547f973bb85fa316937c37ae317779fc309/libs/community/langchain_community/chat_models/ollama.py#L122-L129) which is of type `tool`. 
In order to work around this, within [OllamaFunctions](https://python.langchain.com/v0.2/docs/integrations/chat/ollama_functions/) (a tool calling compatible subclass of ChatOllama) we pass [`ToolMessage` as type `assistant`](https://github.com/langchain-ai/langchain/pull/22339#discussion_r1636772192).

**Comment by ThomasVitale** [comment]
From what I can see, this issue has been fixed in https://github.com/ollama/ollama/pull/5284.

**Comment by tzolov** [comment]
Yep, as of 0.8.2 Ollama supports the `TOOL` message role as well.
Unfortunately it doesn't support streaming function calling yet

**Comment by jmorganca** [comment]
Hi there! Tools are now supported in Ollama. See https://ollama.com/blog/tool-support

**Comment by harishcs01** [comment]
Does the chat function in Ollama support passing a message with the tool role?
