### ISSUE TITLE
Error: pull model manifest: ollama.ai certificate is expired

### ISSUE THREAD

**Issue by hheydaroff** [ollama/ollama#3335]
### What is the issue?

When I try to pull a model from the registry, it gives me the foError: pull model manifest: 
`Get "https://registry.ollama.ai/v2/library/llama2-uncensored/manifests/latest": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: “ollama.ai” certificate is expiredllowing error:`

### What did you expect to see?

Successfull pull of the model, so that I can run it on my local machine.

### Steps to reproduce

1. Open the CLI
2. Run `ollama run dolphincoder` or any other model

### OS

macOS

### Architecture

arm64

### Ollama version

0.1.27

### GPU

Apple

### CPU

Apple

**Comment by BothSavage** [comment]
waiting....

**Comment by szjagoszz** [comment]
same problem here

**Comment by Officialstrike** [comment]
Could you consider closing this issue in favour of #3336? Consolidating the problem into one issue would make it clearer and more organized.  Thanks in advance.

**Comment by tushgaurav** [comment]
I am also waiting on the same issue.

**Comment by mitroe813** [comment]
**What is the issue?**
When I try to pull a model from the registry, it gives me the foError: pull model manifest:
` Get "https://registry.ollama.ai/v2/library/gemma/manifests/2b": tls: failed to verify certificate: x509: certificate has expired or is not yet valid:`

**What did you expect to see?**
Successfull pull of the model, so that I can run it on my local machine.


**Steps to reproduce**
1. Open the powershell
2. Run `ollama run gemma:2b`

**OS**
win11

**CPU**
Intel(R) Xeon(R) CPU E5-2680 v4

**Platform**
No response

**Ollama version**
0.1.29

**GPU**
NVIDIA 

**GPU info**
NVIDIA Quadro RTX 8000

**Comment by dadidelux** [comment]
it does not download unauthorized
