### ISSUE TITLE
OpenAI interface compatible with vector interfaces

### ISSUE THREAD

**Issue by yuanjie-ai** [ollama/ollama#3360]
### What are you trying to do?

OpenAI interface compatible with vector interfaces

### How should we solve this?

OpenAI interface compatible with vector interfaces

### Anything else?

OpenAI interface compatible with vector interfaces

**Comment by yuanjie-ai** [comment]
embedding

**Comment by jmorganca** [comment]
merging with https://github.com/ollama/ollama/issues/2416

Thanks for the issue!

**Comment by john-c-kane** [comment]
I found this issue because i was trying to use Ollama Embeddings API for the Microsoft Semantic Kernel Memory functionality using the OPENAI provider with Ollama URL but I discovered the application is sending JSON format to API as "model" and "input" but Ollama embeddings api expects "model" and "prompt".  So not sure if this is being considered as part of this OPENAI interface compatibility request but wanted to make you aware.
