### ISSUE TITLE
Read each row of CSV into LLM, write each response back out

### ISSUE THREAD

**Issue by 130jd** [ollama/ollama#3403]
I noticed some similar questions from Nov 2023 about reading a CSV in, but those pertained to analyzing the entire file at once.

I have a CSV with values in the first column, going down 10 rows. Each cell contains a question I want the LLM (local, using Ollama) to answer. I will give it few shot examples in the prompt.

I want it to process each question separately, with the instructions and few shot examples above each question. Almost like shutting it down each time, starting it back up, asking a question, then shutting it down and starting it back up, asking another...

Then for the output generated for each question, I want to write them each in an individual row of a new CSV.

It feels conceptually simple but I'm new to this and looking for as close an example that exists so I can follow along. Thanks in advance!

**Comment by wangy4755** [comment]
I tried something similar in R (with rollama package) and tested with Keggle's data (https://www.kaggle.com/datasets/nicapotato/womens-ecommerce-clothing-reviews)

long story short, I pass two column (index and review text) in batches, (batch size=5) and provide the json format example as below in prompt, and also tell the model, expecting 5 reviews and need to output 5 sentiment scores and reasoning.

In my case,  it works better with Mistral instruct and occasionally, the loop may missed a review text, output 4 instead of 5.

################################################################################
# Use For Loop to fit each Batch to LLM
for (i in 1 : num_batch ) {
  
  # Subset Data for Testing Purpose    
  batch_data<-source_data[source_data$batch == i, ]
  
  # set up the task + content for LLM
  task="Conduct analysis on 5 text reivews, one by one, each review need to have one independent output.
        there are always five reviews, do not miss any one. 
          Output must be in JASON Format only. nothing more. follow below example:
          
          [
            {\"sentiment_score\": -0.60, \"reasoning\": \"Reasoning for giving Sentiment Score\"},
            {\"sentiment_score\": -0.80, \"reasoning\": \"Reasoning for giving Sentiment Score\"},
            {\"sentiment_score\":  0.70, \"reasoning\": \"Reasoning for giving Sentiment Score\"},
            {\"sentiment_score\": -0.60, \"reasoning\": \"Reasoning for giving Sentiment Score\"},
            {\"sentiment_score\": -0.60, \"reasoning\": \"Reasoning for giving Sentiment Score\"}
          ]
          
          response start with \"[\" and no words after \"]\"
          the output must always contain 5 jason objects, no more and no less.
          The output must include: Sentiment Score, Reasoning for giving Sentiment Score.
          sentiment_score need to be a score between -1.00 and 1.00.
          
          reasoning, explaining why assigining this score to the review, in plain text only, can not have any smybal
          can not quote from review text. 
          
          
          Here are the review"
  
  content<- batch_data[ ,c("index","Review Text")]
  
  # Merge the task and content for LLM
  q=paste(task, content, sep = ":")
  
  print(paste("Batch:",i))
  
  LLM_output<-query(q,screen=TRUE, model_params = list(temperature = 0.0, seed=47))
  
  output_df <- fromJSON(LLM_output$message$content,simplifyDataFrame=FALSE)
  
  output_df <- data.frame(t(sapply(output_df,c)))
  
  output_df$sentiment_score <- as.numeric(output_df$sentiment_score)
  
  # Append the output
  batch_output<-cbind(batch_data,output_df[ ,c("sentiment_score","reasoning")])
  final_output<-rbind(batch_output,final_output)
  
}

**Comment by 130jd** [comment]
Thank you for sharing that. I haven't used R in almost 10 years and need to relearn it. Did you consider implementing this using Python? Or was R the only/ most feasible way?

**Comment by wangy4755** [comment]
I was inspired by this example (in Python): https://www.youtube.com/watch?v=h_GTxRFYETY&t=727s
hope this helps.
