### ISSUE TITLE
Installation failure on linux due to directory `/usr/share/ollama` not exists

### ISSUE THREAD

**Issue by hualet** [ollama/ollama#3531]
### What is the issue?

Installation failure on linux due to directory `/usr/share/ollama` not exists

➜  ~ curl -fsSL https://ollama.com/install.sh | sh                              

>>> Downloading ollama...
######################################################################## 100.0%##O#- #                                                           ######################################################################## 100.0%
>>> Installing ollama to /usr/local/bin...
请输入密码
验证成功
>>> Adding ollama user to render group...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
>>> Enabling and starting ollama service...
>>> Downloading AMD GPU dependencies...
chmod: 无法访问'/usr/share/ollama': 没有那个文件或目录

### What did you expect to see?

Install success.

### Steps to reproduce

Just run the command `curl -fsSL https://ollama.com/install.sh | sh ` on Linux machine.

### OS

Linux

### Architecture

amd64

### GPU

AMD

### CPU

AMD

**Comment by swoh816** [comment]
You can probably start by where your model blobs are stored, if it is not your first time installing Ollama. Depending on how you use Ollama, model blobs can be located at `/usr/share/ollama/.ollama/`, `$HOME/.ollama/`, or `/root/.ollama/`. Even in Linux, depending on how you use Ollama, model blobs can be in locations other than the Linux default location in `/usr/share/ollama/.ollama/` by default.

**Comment by dhiltgen** [comment]
@hualet I don't see the output from [this](https://github.com/ollama/ollama/blob/main/scripts/install.sh#L84-L87) section of the script, which indicates you already have an `ollama` user on your system, and the home directory must not be `/usr/share/ollama` otherwise the directory should exist.

You might want to follow our docs on [uninstalling](https://github.com/ollama/ollama/blob/main/docs/linux.md#uninstall) first (which includes removing the `ollama` user), then re-run the install and it should work properly

If that doesn't work, let us know and we can do more troubleshooting.
