### ISSUE TITLE
Enable CORS for `file:///` URLs

### ISSUE THREAD

**Issue by jmorganca** [ollama/ollama#3799]
This would help with local development html & javascript apps for Ollama. Important to validate the security risks of this.

**Comment by drazdra** [comment]
as i said at discord, the best way is to add basic "web-server" functionality to ollama.
1. made a single predefined folder in Ollama which will have the files served to users.
2. serve these files through 127.0.0.1:11434/index.html (or other pages)
3. validate file names to allow only /^[-_a-z0-9]{1,32}\.[a-z0-9]{1,5}$/i so there is nothing like "../../" no special chars, etc. test the served file is a real file and not a link before serving it.
4. spit the content of file to the user.

that's it. now the CORS protection is intact, HOST protection is intact and installing a web UI is as easy as putting it into the "web folder" of ollama. 

ideal, super simple and easy to implement, yet still secure. connections are still received only on a configured HOST. Malicious sites can't access local Ollama because their Host is different from the Host of Ollama server and cors will block these. Ideal.

**Comment by airtonix** [comment]
Currently Ollama assumes origins are using the http or https protocol: 

https://github.com/ollama/ollama/blob/4ec7445a6f678b6efc773bb9fa886d7c9b075577/server/envconfig/config.go#L144-L154

I feel like the `OLLAMA_ORIGINS` envvar shouldn't assume that it's http(s) only.
