### ISSUE TITLE
Error: could not connect to ollama app, is it running?

### ISSUE THREAD

**Issue by userandpass** [ollama/ollama#3814]
### What is the issue?

1、modify the ollema.service file
2、systemctl daemon-reload
3、systemctl start ollama

### OS

Linux

### GPU

Nvidia

### Ollama version

ollama --version
Warning: could not connect to a running Ollama instance
Warning: client version is 0.1.32

**Comment by dhiltgen** [comment]
@userandpass can you share your server log?

https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md

**Comment by Mr0519** [comment]
我是在Windows平台遇到了这个错误，经过我多次尝试终于找到了问题。这错误肯定是你更新ollama后产生的错误，问题的原因就是你在Windows的环境配置里把模型存放地址改了，但是重新安装以后无法找到你的配置文件导致的错误。这个问题的修复也很简单就是把原来的模型存放位置改了就行，然后只把模型文件单独拷贝过来就能用了，如果拷贝到新的位置不可用那就只能重新下载模型了。
I encountered this error on the Windows platform, and after multiple attempts, I finally pinpointed the issue. The error is definitely a result of the update to ollama. The problem is that you changed the model storage location in the Windows environment settings, but after reinstalling, the system is unable to find your configuration file, leading to the error. The solution to this problem is quite straightforward: simply change the model storage location back to the original setting, and then copy only the model files over. If copying to the new location doesn't work, then you will need to download the model again.

**Comment by ergosumdre** [comment]
> sudo chown -R ollama:ollama

Thanks, this helped alot. Since I created a different folder i had to give ollama permissions to the new folder by:
`sudo chown -R ollama:ollama FOLDER_PATH`

**Comment by dhiltgen** [comment]
@userandpass if you're still having trouble, please make sure to upgrade to the latest version and if that doesn't resolve it, please share the server logs and I'll reopen this issue.

**Comment by P-ek** [comment]
You need to launch Ollama before you can pull or run models, in the case of a local attempt, you would simply run (after installing Ollama):

`ollama serve`

Open new prompt and you would subsequently be able to run "your model":

`ollama run your model`
