### ISSUE TITLE
setting OLLAMA_HOST to 0.0.0.0 could make the API to listen on the port using IPv6 only

### ISSUE THREAD

**Issue by TadayukiOkada** [ollama/ollama#3961]
### What is the issue?
Edit2: sorry, if you set BindIPv6Only, 0.0.0.0:11434 should use v4. so this shouldn't be a problem.

Edit: by default, it seems it'll listen on both v4 and v6. If you set BindIPv6Only in systemd.socket, or /proc/sys/net/ipv6/bindv6only is set to 1, it may not listen on v4.

Ollama is only listening on IPv6 with OLLAMA_HOST=0.0.0.0:
```
# netstat -anp | grep 11434
tcp6       0      0 :::11434                :::*                    LISTEN      5009/ollama
```
This seems to be the cause:
https://github.com/golang/go/issues/48723

### OS

Linux

### GPU

Nvidia

### CPU

Other

### Ollama version

0.1.32

**Comment by martindale** [comment]
What's the fix?

**Comment by nuaimat** [comment]
i believe this might be the root of all problems related to open webui docker. 

when i get into the docker container for open webui:
`docker exec -it open-webui  bash`

then execute: 
` curl --ipv4  http://host.docker.internal:11434/api/tags` 
i get a response

but when i do:
`curl --ipv6  http://host.docker.internal:11434/api/tags`

setting up ipv6 is a topic by itself: https://docs.docker.com/config/daemon/ipv6/ 


i believe the fix for this is to parse OLLAMA_HOST 
if it was "0.0.0.0" then listen to ipv4 interface 
if it was "::" then listen to ipv6 interface 

or make it easier and listen to both ipv6 and ipv4 interfaces by default. 

just like what openssh server is doing for example:
```
sudo netstat -nutlp  | grep 22
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      697/sshd: /usr/sbin
tcp6       0      0 :::22                   :::*                    LISTEN      697/sshd: /usr/sbin

```

**Comment by bojake** [comment]
This bug still persists as of 1/29/2025.

Jan 29 09:43:20 ollama[410734]: time=2025-01-29T09:43:20.124-08:00 level=INFO source=routes.go:1238 msg="Listening on [::]:11434 (version 0.5.7)"

in the override.conf:

[Service]
Environment="OLLAMA_HOST=0.0.0.0"

netstat:
tcp        0      0 127.0.0.1:57406         127.0.0.1:11434         TIME_WAIT   -
tcp6       0      0 :::11434                :::*                    LISTEN      410734/ollama

**Comment by bojake** [comment]
FYI. I had to follow guidance on this page: https://askubuntu.com/questions/309461/how-to-disable-ipv6-permanently to disable ipv6 via grub and then I was able to run ollama in ipv4 "relic" mode:

tcp        0      0 0.0.0.0:11434           0.0.0.0:*               LISTEN

**Comment by stratbasher** [comment]
Experiencing this issue as well - only listening on ipv6 when setting OLLAMA_HOST to 0.0.0.0 via systemctl edit ollama.service

**Comment by Nejjer** [comment]
I have the same problem

**Comment by MDBrothers** [comment]
Same problem in Ollama 0.3.13 installed via Ubuntu snaps
