### ISSUE TITLE
Error: exception error loading model architecture: unknown model architecture: 'phi3'

### ISSUE THREAD

**Issue by atb29** [ollama/ollama#4002]
### What is the issue?

when trying to import a custom gguf model that i downloaded locally and import it to ollama ,i got this error 
"(myenv) E:\phi3-mini-128k-gguf\model>ollama list
NAME                            ID              SIZE    MODIFIED
phi-3-mini-128k-Q4_K_S:latest   31a2fd935902    2.2 GB  3 minutes ago

(myenv) E:\phi3-mini-128k-gguf\model>ollama run phi-3-mini-128k-Q4_K_S:latest
Error: exception error loading model architecture: unknown model architecture: 'phi3'
"
here is the modelfile used 
FROM ./Phi-3-mini-128k-instruct.Q4_K_S.gguf

TEMPLATE """
{{ if .System }}<|system|>
{{ .System }}<|end|>
{{ end }}{{ if .Prompt }}<|user|>
{{ .Prompt }}<|end|>
{{ end }}<|assistant|>
{{ .Response }}<|end|>
"""

PARAMETER stop <|user|>
PARAMETER stop <|assistant|>
PARAMETER stop <|system|>
PARAMETER stop <|end|>
PARAMETER stop <|endoftext|>

note : everything was fine when i used the ollama create phi-3-mini-128k-Q4_K_S ./Modelfile

### OS

Windows

### Ollama version

0.1.31

**Comment by BruceMacD** [comment]
Hi @atb29, sorry about this. It will be fixed in the next release (very soon), we just needed to update our version of llama.cpp.

Resolving this one for now since the release is coming very soon, the `v0.1.33` pre-release is at the top of the releases page if you'd like to keep track of it:
https://github.com/ollama/ollama/releases

**Comment by atb29** [comment]
Thanks guys for your replay 🙏:)
