### ISSUE TITLE
Ollama.com - Pull Statistics can be easily fooled

### ISSUE THREAD

**Issue by electricalgorithm** [ollama/ollama#4003]
### What is the issue?

Ollama.com model statistics include a pull count. The pull count statistic provides users with the "popularity" of models, where it seems that it is easy to increase the pull count.

**Code Reapply**
By using the following Python code snippet, you can increase the amount of pulls a hundred times.

```python
import subprocess
import time
import signal
import os

for i in range(1000):
    process = subprocess.Popen(["ollama", "pull", "USERNAME/MODELNAME"])
    time.sleep(1)
    try:
        os.kill(process.pid, signal.SIGTERM)
    except ProcessLookupError:
        pass
```

Note that 2-3 minutes is needed to see the changes on the UI.

**Suggestion**
Pull statistics must be increased after the whole model is pulled into a machine, not after starting a pull request.

I'm not a Go dev, don't think that I can provide a fix in a short time.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.32

**Comment by electricalgorithm** [comment]
I've applied the technique to a model of mine. Within the bug, we can achieve more than 1k pulls in under 20 minutes.

<img width="805" alt="resim" src="https://github.com/ollama/ollama/assets/27111270/dcdbba0c-2a70-4b42-ad90-edade4b08224">

You can imagine that no one would find a model published an hour ago & install it quickly, right? 😄

**Comment by pdevine** [comment]
Hey @electricalgorithm , we're actually counting pulls the same way as Docker counts them, i.e. if the manifest gets pulled it counts as a pull. The reason why is because models can share content, and it's not always necessary to re-pull an entire contents of a model.

I think the solution will be to introduce throttling which will prevent you from hitting that API repeatedly. I'm reluctant to _stop_ people from pulling though until it's clear that it's being abused.

**Comment by jmorganca** [comment]
Hi @electricalgorithm thank you so much for the issue. Will close this for now if that's ok just since there are quite a few issues open and we are hoping to lower that 😊 . That said don't hesitate to create new issues!
