### ISSUE TITLE
Windows installation is behaving like malware

### ISSUE THREAD

**Issue by eabase** [ollama/ollama#4048]
### What is the issue?

This is beyond bad. 

1. It installs stuff all over the place, without informing the user. 
```
	C:\Users\xxxx\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
	C:\Users\xxxx\AppData\Local\Temp\ollamaNNNNNN
	C:\Users\xxxx\.ollama\id_ed25519
	C:\Users\xxxx\AppData\Local\Programs\Ollama
	C:\Users\xxxx\AppData\Local\Ollama
```
2. It doesn't ask the user where they want it to be installed!
3. It opens ports and starts a server under different application name and on unspecified sever ports that can only be found in a temp directory.
4. Once the original (cmd) windows is closed, the server is still running!
5. There are no instructions on how to shut down the server

In the current state this application is acting more like **malware** than something serious.

### OS

Windows

### GPU

Nvidia

### CPU

Intel

**Comment by WolfTheDeveloper** [comment]
1. Did you download from the website?
2. If you did, those file locations look correct, and Ollama runs in the background when your computer starts so you can use the models supported by Ollama at anytime without having to start the app.

The issue with downloading without asking the path might be an issue with the installer. Otherwise, Ollama was built to run in the background. Ollama is not malware.

**Comment by liaosu0755** [comment]
> 1. Did you download from the website?
> 2. If you did, those file locations look correct, and Ollama runs in the background when your computer starts so you can use the models supported by Ollama at anytime without having to start the app.
> 
> The issue with downloading without asking the path might be an issue with the installer. Otherwise, Ollama was built to run in the background. Ollama is not malware.

I'm having the same problem, I'm trying to install ollama as well as the models to other partitions instead of the system partition, but I can't do it.

**Comment by dhiltgen** [comment]
In 0.1.33 we've moved to a more conventional packaging model on Windows where all the executables are in the installer instead of carrying them as payloads in the primary CLI.  We've also added a zip file with all the components for folks who want to roll their own installation models in advanced use-cases.  The pre-release is available at https://github.com/ollama/ollama/releases

@liaosu0755 you can adjust the location of the models by adjusting an environment variable - see https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored

Fine-grain control over the installer location is tracked in #2776

**Comment by eabase** [comment]
@dhiltgen 

Please reconsider your install paths.  
No serious package is putting huge models under a dotted sub-directory in home, especially on Windows.

Comfortably closing the issue, does not solve the problem. The problem is that ollama is behaving like malware, for all sorts of reasons, including and not limited to the ones I stated above. But mostly for lack of informing the user what the installer is about to do. 

> *Fine-grain control over the installer location is tracked in* #2776 

You could also have answered:  
```powershell
$Env:OLLAMA_MODELS = 'C:\LLM\models'                                    # User
[Environment]::SetEnvironmentVariable('OLLAMA_MODELS','C:\LLM\models')  # System 
```

Please put all environment variables in your README, so users doesn't have to waste time finding out about this, only after having completed installation.

**Comment by tetsuoo-online** [comment]
I agree with eabase. I have a 16Tb disk + 2Tb SSD + 500 Gb nvme but most of the time I can't even use them because so many programs force themselves in C: system disk, I hate it.
Here I just installed Ollama with 1 model, I have now 495Mb left. This is a neverending fight with the programs even though I have plenty of storage space, a custom install option is essential

**Comment by dhiltgen** [comment]
@eabase Ollama is a client-server architecture.  The server keeps track of the models, and the client keeps track of history.  We don't currently have a way to alter where the client stores state; it will always be in your home directory.

**Comment by eabase** [comment]
@dhiltgen 
Thanks for clarification. One last, question: 
(a) What is placed in this history folder? 
(b) How large can it get?
