### ISSUE TITLE
WithSecure quarantined ollama_llama_server.exe as harmful file / Malware

### ISSUE THREAD

**Issue by sjdevcode** [ollama/ollama#4134]
### What is the issue?

After updating Ollama to version 0.1.33 WithSecure Elements identified ollama_llama_server.exe as a harmful file and put it in quarantine. It classified it as "Category: Malware and Type: Exploit".

It's about ollama_llama_server.exe in the \ollama_runners\cpu_avx folder. The executables in the other ollama_runners folders are unaffected.

I assume it's a false positive. However, a solution is highly appreciated.  

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.33

**Comment by dhiltgen** [comment]
Sorry you hit this.  I've submitted our binaries to WithSecure's false positive form.  I didn't see a mention of their turn-around time, but most AV vendors are a few days I believe.  If you're still seeing false positives by next week, please let us know.

**Comment by sjdevcode** [comment]
Thank you for your quick response. I will get back to you next week if I keep seeing false positives.

**Comment by americium241** [comment]
Hello fyi i ran in similar flagging by WithSecure today morning.
7 mai 2024 09:59:48 UTC
Exploit:W32/CVE-2020-0601.I|Quarantined|On_access_scanner.file_infection.quarantine|...Ollama\ollama_runners\cpu_avx\ollama_llama_server.exe
OS : windows

**Comment by dhiltgen** [comment]
@americium241 since I've already uploaded the binaries to WithSecure for false positive resolution, I'm not sure me submitting them again will help.  Since you have a business relationship with the company, can you try to submit them as well to see if that does the trick?

If I had to guess why this happened, there are malicious actors using Go to build malware, so we've seen various AV vendors trigger false positives as a result since we're also written in Go.

**Comment by sjdevcode** [comment]
@dhiltgen I‘ve submitted the file in question (ollama_llama_server.exe from the cpu_avx folder) to WithSecure via their built in reporting form on May 3rd.

**Comment by dhiltgen** [comment]
@sjdevcode has the false positive gone away or does WithSecure still flag Ollama?

**Comment by sjdevcode** [comment]
@dhiltgen I've run the installation process today and no false positive showed up for me.
