### ISSUE TITLE
account for common config/data locations when OLLAMA_MODELS is unset

### ISSUE THREAD

**Issue by asmrtfm** [ollama/ollama#4180]
Many, probably most,  projects out there which interface with ollama - such as open-webui and privateGPT end up setting the OLLAMA_MODELS variable thus saving models in an alternate location - usually within the users home directory.

This can become problematic considering the chronic instability of these projects where a single variance in one's environment can lead to edge cases that are undocumented.
I encountered one such issue and resolved to just use ollama itself in the terminal and not worry about a gui on top of it.
I pulled down like a hundred gigabytes of models with `ollama pull <MODEL>`.
I used them in the terminal for a while (`ollama run <MODEL>`)
After restarting my machine the models are no longer showing up.
I check the docs, they say they will be under /usr/share/ollama/.ollama/models/registry.ollama.ai/...

I freaked out, but then realized what had happened.
However, I thought it was worth pointing out that there is a long-standing convention for programs to look for configs/data/whatever in additional common locations, such as ~/.ollama

Just a thought.  Not a big deal.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.33

**Comment by pdevine** [comment]
Given _most_ users on Linux aren't using it on the desktop, we opted to install Ollama into a centralized place (unlike in Windows and MacOS), which is why it uses `systemd` by default. It is possible to build/run it yourself though on Linux and have it store everything in `~/.ollama`.

It just seemed like most people wouldn't want to do that? I'll go ahead and close the issue, but feel free to keep commenting.
