### ISSUE TITLE
kernel:do_IRQ: 1.46 No irq handler for vector (irq -1)

### ISSUE THREAD

**Issue by lonngxiang** [ollama/ollama#4347]
### What is the issue?

run error

### OS

Linux

### GPU

Nvidia

**Comment by lonngxiang** [comment]
![image](https://github.com/ollama/ollama/assets/40717349/ddf49fcb-097f-4c90-accd-d8a22b392b86)

**Comment by dhiltgen** [comment]
Are you running the latest nvidia driver? 
Do other GPU applications work properly on this system? 
What does `nvidia-smi` report on your system? 
Does ollama hang with the spinner, or does it eventually load the model and work on GPU or CPU?

If the above don't clear up what the problem is, please share the server log.
https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md
