### ISSUE TITLE
Nvidia Jetson Nano can not use GPU to run ollama

### ISSUE THREAD

**Issue by Dominic23331** [ollama/ollama#4376]
### What is the issue?

I use Jetson Nano to run ollama, but when I check jtop, I find my GPU is not work, the ollama is running in CPU. How to solve this problem?
![image](https://github.com/ollama/ollama/assets/53283758/a3db77bd-5094-4e2a-b1a2-344db059b5cf)

### OS

Linux

### GPU

Nvidia

### CPU

Other

### Ollama version

0.1.37

**Comment by buraksumer** [comment]
The same problem applies to me too.

System;
windows 11
Nvidia RTX 4090
128gb memory
i7-12700K

**Comment by dhiltgen** [comment]
@Dominic23331 it sounds like our pre-built binaries might not be compatible with the cuda driver/library on the host.  The server log will likely show more details on why we couldn't load properly on the GPU.  I believe others have reported that building from source gets Ollama linked to the right cuda library for this system and should work as a workaround until we can figure out why our prebuilt arm binaries aren't working.

@buraksumer your issue is most likely something else unrelated to the ARM Jetson platform.  Please go ahead and find a new issue with your server log so we can see why it's not detecting your GPU.  (please make sure to upgrade to the latest version)

**Comment by dhiltgen** [comment]
We'll track Nano support in #4140
