### ISSUE TITLE
Possible to add numDownloadParts as option?

### ISSUE THREAD

**Issue by Gomez12** [ollama/ollama#4595]
Currently in server/download.go there is a constant : numDownloadParts          = 64

And basically I would like to see it as an option to either change the value or simply put it to 1.

Currently it is overloading my router (which does content inspection) and then my whole network almost has no internet any more.

It also blocks itself I think and it will errorOut with : max retries exceeded.
Then the network works fine again, until I restart the Ollama pull (which continues fine) and then the internet goes down again.

**Comment by coolljt0725** [comment]
i have the similar issue, I opened a PR https://github.com/ollama/ollama/pull/4627 to add `OLLAMA_MAX_DOWNLOAD_PARTS` env to set max download parts

**Comment by tensiondriven** [comment]
Same issue here.  I have a 30mbps downlink from the internet, and downloading a model will saturate my connection to the point where other traffic will time out.  One or two download threads would suffice, but as is I'm unable to affect that.  

Who has merge rights?  This would be a great thing to get added in.

**Comment by jmorganca** [comment]
Hi folks, the default number of parts has since been updated to 16 (from 64) which, from our testing, should resolve most bandwidth issues. Let me know if this isn't the case and we can re-open. Thanks so much for the issue!

**Comment by gera2ld** [comment]
I've encountered this issue at my company where the bandwidth is limited to about 30 Mbps per device. This issue causes downloads to fail and restart indefinitely because the threads block each other, and all other traffic times out. (exactly the same as OP)
While it's acceptable for it to block other traffic temporarily, it also blocks itself, preventing the download from ever finishing.

Could you please reopen this and add an option to limit concurrency?
