### ISSUE TITLE
more types of models

### ISSUE THREAD

**Issue by zsq2010** [ollama/ollama#4644]
could we have more type of modles like，vision model，tts，ocr，etc

**Comment by dhiltgen** [comment]
Lets track these with discrete issues since these will be supported with different models.

Some vision models are already supported like [llava](https://ollama.com/library/llava) and [blakllava](https://ollama.com/library/bakllava)   If there are other vision models we don't yet support you'd like to see, please submit model requests for them.

Voice/speach is tracked via #1168 

For OCR, llava 1.6 is claimed to have better OCR performance, and is available.  If there are other specific models for OCR you'd like to see please submit model requests for those.
