### ISSUE TITLE
Ollama should error with insufficient system memory and VRAM

### ISSUE THREAD

**Issue by jmorganca** [ollama/ollama#4955]
### What is the issue?

Currently, Ollama will allow loading massive models even on small amounts of VRAM and system memory, leading to paging to disk and eventually errors. It should limit the size of models to avoid errors.

**Comment by dhiltgen** [comment]
This is partially addressed in #4517 although the system memory logic kicks in for concurrency, so a little refactoring will be required to prevent a single model load.

**Comment by denisidoro** [comment]
Could you please consider adding a flag to optionally skip this check?

Context: I used to run a model just fine on my phone (for my non-prod purposes), but now I'm unable to do so

**Comment by dhiltgen** [comment]
@denisidoro can you share more information about your scenario?  How much physical memory, how much swap space, is there a GPU involved or are you just doing CPU inference, what model are you trying to load?  The goal of this check is only to block model loads that will hit OOM crash scenarios, so if you have a scenario that can load the model which we're blocking, that's not the intent and something we'd like to fix.

**Comment by denisidoro** [comment]
Thanks for the reply

Model: gemma2:2b

Device: a Xiaomi 9T Pro running Termux

Memory: the device has 5.7GB total RAM; the OS tells me I around 3.5GB free or so, but when I try to run the model, Ollama says it needs 3.3GB but there's only 2.1GB available (I'm not really sure why there's this gap between what the OS sees and what Termux sees)

**Comment by dhiltgen** [comment]
@denisidoro we use `/proc/meminfo` to discover the available resources on the system.

**Comment by RecentlyRezzed** [comment]
@dhiltgen I think the problem with Termux/Android is the different memory management in comparison to Linux.

As phones didn't have a lot of memory, the apps have to save their state because they will be killed when another a app needs the memory and have to be OK with it. On the other hand, starting apps consumes CPU cycles and this consumes power. So Android wants to keep as much apps in memory as possible.

I think that leads to a situation where OOM-killing is kind of the normal state when running Android. On Android, Ollama should just take the memory it needs. Other apps have to move out of the way. And if Ollama itself gets killed, the model was to big.

Maybe someone with more knowledge can give a better answer.

**Comment by dhiltgen** [comment]
@RecentlyRezzed mobile devices aren't officially supported, so the code doesn't currently have any special case logic for dealing with their memory model.  We're tracking mobile support in issue #1006

**Comment by ShayBox** [comment]
I didn't know this was already a feature, because it's never once shown me the error. Every time I try to load a 72b model it reserves all my VRAM, RAM, and SWAP, then my computer freezes. If I manually kill it before I freeze my RAM is still used and does not free until I restart, there's a memory leak in Ollama and this error message never works.

**Comment by dhiltgen** [comment]
@ShayBox some users want to be able to overflow into swap to load very large models and are OK with their system thrashing to achieve very slow inference, so we consider available swap space as part of our upper bound of model size.

Ollama uses a subprocess for running inference, and by killing just the parent with a -9, we don't have a chance to clean up our child process.  If you look for `ollama_llama_runner` and kill that process, your system should recover.
