### ISSUE TITLE
0xc0000409 error with llava-phi3

### ISSUE THREAD

**Issue by razvanab** [ollama/ollama#4979]
### What is the issue?

I get the 0xc0000409 error with llava-phi3 when OLLAMA_FLASH_ATTENTION is enabled.

RAM = 32GB

GPU = GTX 1060
VRAM = 6GB

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.42

**Comment by AncientMystic** [comment]
Pascal gpus do not officially support flash attention due to their lack of tensor cores and require a FP32 non tensor core vector kernel which has been recently updated for support in llama.cpp and i am not sure if ollama is using a recent enough version of llama.cpp as it should provide almost a 2x boost in tokens per second, which i notice no difference on my tesla p4

**Comment by dhiltgen** [comment]
It sounds like we can close this issue.    Eventually our goal is to get flash attention turned on automatically based on if the GPU can support it, but until then, the experimental env var can be used to enable manually.

**Comment by AncientMystic** [comment]
> It sounds like we can close this issue.    Eventually our goal is to get flash attention turned on automatically based on if the GPU can support it, but until then, the experimental env var can be used to enable manually.

It does seem to be solved and it would be really nice to see the fp32 vector kernel flash attention supported on ollama (doesn't seem to be yet but from my understanding it is now in the last month on llama.cpp) as many of us are still on pascal which also has crippled fp16 performance, that plus the recently added kv quant should really benefit pascels
