### ISSUE TITLE
Make "pull" support more than one model

### ISSUE THREAD

**Issue by Speedway1** [ollama/ollama#5141]
"ollama pull " currently only supports one parameter. However when setting up a new server, or when do a bulk update of LLMs, we need to do a batch of LLM pulls.

It would be very handy for the command to support more than one model as parameter.

E.g.
    ollama pull  deepseek-coder-v2 phi3:14b codestral

As opposed to:
for i in deepseek-coder-v2 phi3:14b codestral
do 
 ollama pull $i
done

It also means that the job can be given a nohup and booted into background and for longer downloads it can simply run as a background task until all the models are pulled.

**Comment by chrisoutwright** [comment]
On slower internet connections, I often couldn't complete even one download...even on high-speed cable, I would occasionally get stuck near the end (will become very slow for the last percentages)
I'm curious about how the partial files will be managed during multiple simultaneous pulls and what if one would fail (partial gone then?)? Additionally, in Windows 10, a single pull completely blocks bandwidth; I wouldn't even be able to open a site properly due to many simultaneous connections for each pull (possibly due to the federated fetch mode).
Do we have improvements to those challenges? This would help the feature I guess.
