### ISSUE TITLE
keep_alive and OLLAMA_KEEP_ALIVE not effective

### ISSUE THREAD

**Issue by peanutfs** [ollama/ollama#5272]
### What is the issue?

* After Ollama starts the qwen2-72b model, if there is no interaction for about 5 minutes, the graphics memory will be automatically released, causing the model port process to automatically exit. 
* I want the model to continue to exist, so I tried setting OLLAMA_KEEP_ALIVE=-1 in ollama.service, and also setting keep-alive=-1 when calling the interface. However, it does not take effect.  I also tried setting keep_alive=24h with `ollama run qwen2:72b --keepalive 24h`, but it didn't work either.
* I used nvidia-smi to check and there were no running processes. 
* The graphics card is NVIDIA GeForce RTX 3090 24G * 8
* CUDA Version: 12.5

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.44

**Comment by lstep** [comment]
It works for me. Using Ubuntu Linux:
Created a `/etc/systemd/system/ollama.service.d/override.conf`:

```
Environment="OLLAMA_HOST=0.0.0.0"
Environment="OLLAMA_MODELS=/home/lstep/workspace/Apps/OLLAMA/models"
Environment="OLLAMA_ORIGINS=*"
Environment="OLLAMA_FLASH_ATTENTION=1"
Environment="OLLAMA_KEEP_ALIVE=-1"
User=myusername
Group=myusername
```

Then `systemctl daemon-reload` and restart the ollama server with `systemctl restart ollama`. Try to load a model (for example `ollama run deepseek-coder-v2:16b-lite-instruct-q8_0`. 
And to check it is loaded "forever", use `ollama ps` which should show `UNTIL forever`:

```
$ ollama ps
NAME                                            ID              SIZE    PROCESSOR       UNTIL   
deepseek-coder-v2:16b-lite-instruct-q8_0        44250301ba51    19 GB   100% GPU        Forever
```

**Comment by peanutfs** [comment]
Thank you for your reply. When I run the model on my machine, I set keep_alive. If I call the model interface remotely without setting keep_alive, the previously set keep_alive will become invalid. Is this scene normal?

**Comment by peanutfs** [comment]
I just tested it and I'm sorry for the feedback that keep_alive doesn't work. `ollama run qwen2:72b --keepalive 24h` is effective, but as I said above, when I call the interface remotely, UNTIL will change from `24 hours from now` to `4 minutes from now`. Is this normal?

**Comment by lstep** [comment]
> I just tested it and I'm sorry for the feedback that keep_alive doesn't work. `ollama run qwen2:72b --keepalive 24h` is effective, but as I said above, when I call the interface remotely, UNTIL will change from `24 hours from now` to `4 minutes from now`. Is this normal?

What do you mean by "calling remotely" exactly? Using the ollama-webui?

**Comment by peanutfs** [comment]
My ollama host is 0.0.0.0, port is 11434, then I use a domain name to forward the request to port 11434 of the ollama server. When calling with the domain name, the above situation will occur.
My request method is openai api, and keep_alive is not set. I tested that if I use `ollama run qwen2:72 --keepalive 24h`, then after the call, UNTIL will become `4 minutes from now`. When using `OLLAM_KEEP_ALIVE=-1`, the call is normal, and UNTIL is still forever

**Comment by dhiltgen** [comment]
I think there is a bug here.  The intent on this settings is if unset by the client, any prior setting should be respected, but the following shows it reset to the default ~5 minute setting:

```
% ollama run llama3 --keepalive 1h hi
Hi! It's nice to meet you. Is there something I can help you with or would you like to chat?

% ollama ps
NAME         	ID          	SIZE  	PROCESSOR	UNTIL
llama3:latest	365c0bd3c000	6.7 GB	100% GPU 	59 minutes from now
daniel@tater07:~$ curl http://localhost:11434/api/generate -d '{
  "model": "llama3",
  "prompt": "hi",
  "stream": false
}' > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   592  100   532  100    60    787     88 --:--:-- --:--:-- --:--:--   877
% ollama ps
NAME         	ID          	SIZE  	PROCESSOR	UNTIL
llama3:latest	365c0bd3c000	6.7 GB	100% GPU 	4 minutes from now
```

**Comment by amirvenus** [comment]
How can I use it with serve as I currently do this:

`OLLAMA_HOST=0.0.0.0 ollama serve`

**Comment by dhiltgen** [comment]
@amirvenus something like would work:
```
OLLAMA_HOST=0.0.0.0 OLLAM_KEEP_ALIVE=1h ollama serve
```

**Comment by xgdgsc** [comment]
![image](https://github.com/user-attachments/assets/92ed891c-ba87-458a-a4d2-9add8603e1f7)

Why doesn' t it keep the model in memory with this serve ? From the screenshot you can see the OLLAMA_KEEP_ALIVE is set to -1.

**Comment by dhiltgen** [comment]
@xgdgsc it works for me, so I'm not sure what's going on.
```
OLLAMA_KEEP_ALIVE=-1 ollama serve
```

```
% ollama run orca-mini hello
 Hello there! How can I assist you today?
% ollama ps
NAME                ID              SIZE      PROCESSOR    UNTIL
orca-mini:latest    2dbd9f439647    5.9 GB    100% GPU     Forever
```

My best guess is your client is setting it to something.  The server setting establishes the default, but a client can still request a different value.

**Comment by Zeeeeta** [comment]
Same issue here, I use curl to set a particular model's keep_alive to -1, but after a call from llamaindex (without setting any keep_alive), it is reset to expire after 5 mins.

But when call from Open WebUI, the FOREVER is retained, I am not sure if Open WebUI first query existing setting and apply to its call or what.

I am not using the env var OLLAMA_KEEP_ALIVE because I don't want FOREVER to apply to all models.

**Comment by ankos792** [comment]
I have same problem. It used to work, but now the systemctl edit ollama and there:
Environment="OLLAMA_NUM_PARALLEL=6"
Environment="OLLAMA_MAX_LOADED_MODELS=3"
Environment="OLLAMA_MAX_QUEUE=256"
Environment="OLLAMA_KEEP_ALIVE=-1"

Environment="OLLAMA_HOST=0.0.0.0"

these are not effective. 

Also they are in the override.conf file.

/etc/systemd/system/ollama.service.d/override.conf:1: Assignment outside of section. Ignoring.

**Comment by MiMoHo** [comment]
I'm facing the 5 minutes timeout issue on an n8n setup serving my Supabase data ingest with Ollama running from Docker Desktop on an Apple Silicon Mac. I create a container from Ollama in Docker specifying variable `OLLAMA_KEEP_ALIVE` with value `24h` in the _Environment variables_.

@dhiltgen You have an unfavorable typo [above](https://github.com/ollama/ollama/issues/5272#issuecomment-2411701139). Even when setting the correct variable "OLLAM**A**_KEEP_ALIVE", the text-ingest task to my database is aborted when exceeding 300 seconds. I couldn't set yet another `keep_alive` parameter in the run command for non-generative embedding models.

People, please mind to write `keep_alive` with the underscore as it seems to be relevant according to the [documentation](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately). It should deal briefly with Docker Desktop setups as you don't use curl commands there.

Why is there actually a default stop parameter when you can `stop` running a model anytime? When I run out of RAM, I know that I just have to quit Ollama, otherwise, I want to use the running model. A 5 minute timeout is unexpected and unhelpful in regular usage!

Maybe we should reopen this issue as the title applies also to other setups that are apparently still not working.

**Comment by DY-ATL** [comment]
How to make OLLAMA_KEEP_ALIVE effective in the ollama official docker? I cannot restart the ollama via `systemctl restart ollama` because there is no `systemctl`.

**Comment by DY-ATL** [comment]
I had the same problem as https://github.com/ollama/ollama/issues/5272#issuecomment-2188709424. If I run `ollama run deepseek-r1:671b`, then the UNTIL is as expected. However, if I use Chrome extension **Page Assist**, the UNTIL is still default 5 min.

**Comment by SuperJunier666** [comment]
> I had the same problem as [#5272 (comment)](https://github.com/ollama/ollama/issues/5272#issuecomment-2188709424). If I run `ollama run deepseek-r1:671b`, then the UNTIL is as expected. However, if I use Chrome extension **Page Assist**, the UNTIL is still default 5 min.我遇到了与 [#5272 (comment)](https://github.com/ollama/ollama/issues/5272#issuecomment-2188709424) . 相同的问题。如果我运行 `ollama run deepseek-r1：671b`，则 UNTIL 符合预期。但是，如果我使用 Chrome 扩展 **Page Assist**，则 UNTIL 仍默认为 5 分钟。

I'm having the same problem, do you have a solution?

**Comment by tzelalouzeir** [comment]
> How to make OLLAMA_KEEP_ALIVE effective in the ollama official docker? I cannot restart the ollama via `systemctl restart ollama` because there is no `systemctl`.

If you are using docker you need to forget about the systemctl ollama service and instead use docker restart ollama_gpu, also you need to set environment variables before the build the container due to you can't access to env with systemctl, for example ollama_gpu usage:

```docker-compose.yml```:
```
services:
  ollama_gpu:
    image: ollama/ollama
    container_name: ollama_gpu
    environment:
      - OLLAMA_FLASH_ATTENTION=1
    ports:
      - "11434:11434"
    volumes:
      - ollama_gpu:/root/.ollama
    runtime: nvidia

volumes:
  ollama_gpu:
```

**Comment by AndregoVersailles** [comment]
so, the way to work around this, because the OP is clearly using windows and the given codes are in mac, as stated above, is:
ollama run (client of choice) --keepalive 999999h
It will not accept more than 1 million hours, and will only accept hours as a medium when using windows.  It assumes this to be the mac's version of "-1", which it will not accept as a variable.  So when you do your ollama ps it spits out "UNTIL Forever".

**Comment by snailwei** [comment]
> Environment="OLLAMA_KEEP_ALIVE=-1"

This works for me

```
sudo systemctl stop ollama
sudo vim /etc/systemd/system/ollama.service.d/override.conf
sudo systemctl daemon-reload
sudo systemctl start ollama
```

```
[Service]
Environment="OLLAMA_HOST=0.0.0.0:11434"
Environment="OLLAMA_ORIGINS=*"
Environment="OLLAMA_KEEP_ALIVE=-1"
```

**Comment by dimensiondata** [comment]
in ollama.service:   OLLAMA_KEEP_ALIVE=-1   , it is not effective.

the reason is below:

keep_alive covers  `OLLAMA_KEEP_ALIVE=-1`.

when i remove this params.  it is effective.

ollama ps
NAME                     ID              SIZE     PROCESSOR    UNTIL
qwen3-14b-0129:latest    aa27a159c061    15 GB    100% GPU     **Forever**

```python
    payload: Dict[str, Any] = {
        "model": model,
        "messages": messages,
        "options": options,
        "stream": True,
        #"keep_alive": keep_alive,
        #"keep_alive": "-1"
    }
    with requests.post(url, json=payload, stream=True, timeout=timeout) as r:

```
