### ISSUE TITLE
dolphin-phi3 and dolphin-qwen2

### ISSUE THREAD

**Issue by botollama** [ollama/ollama#5384]
dolphin-phi3 and qwen2 dolphin https://huggingface.co/cognitivecomputations
can we have this models so people can us them like dolphin-llama3

**Comment by rjmalagon** [comment]
Hi @userforsource, I uploaded dolphin-qwen2 on https://ollama.com/rjmalagon, if you need a particular quantized of either model for yourself, I may help you with individual gguf files or uploads to my online Ollama library, while waiting for official uploads.

**Comment by userforsource** [comment]
Thanks but i use alpaca so. This need to be in the ollama list to use with that.

**Comment by rick-github** [comment]
alpaca runs a local ollama server, so you can communicate with it directly.  On my machine it's localhost:11435 because I already have an ollama server at 11434.  To download rjmalagon's dolphin-qwen model:

```
curl localhost:11435/api/pull -d '{"name": "rjmalagon/dolphin-2.9.2-qwen2-7b-f16"}'
```
Then click on the books icon ("Manage models") icon next to the model selector and the new model should appear in the list.

Note that [CognitiveComputations](https://huggingface.co/cognitivecomputations) started the dolphin work, and they [upload their models](https://ollama.com/search?q=cognitivecomputations&p=1) to ollama, so you can get their phi3 model from there.

**Comment by pdevine** [comment]
@botollama as @rick-github mentioned, the official versions of those can be found in:

https://ollama.com/CognitiveComputations/dolphin-qwen2

and

https://ollama.com/CognitiveComputations/dolphin-phi-3

I'll go ahead and close the issue.
