### ISSUE TITLE
ollama push suddenly not working / giving not authorized error

### ISSUE THREAD

**Issue by ashokgit** [ollama/ollama#5456]
### What is the issue?

Hi, I get the following error on push 

ollama push myuseer/model-name

retrieving manifest 
pushing 663944096011... 100% ▕█████████████████████████████▏ 667 MB                         
pushing c3be5dc5651b... 100% ▕█████████████████████████████▏   54 B                         
pushing 1cb5df2a171b... 100% ▕█████████████████████████████▏   32 B                         
pushing 395c6bda52c3... 100% ▕█████████████████████████████▏  413 B                         
pushing manifest 
Error: you are not authorized to push to this namespace, create the model under a namespace you own

I've followed the push model guidelines. 
also copied ~/.ollama/id_ed25519.pub
and  /usr/share/ollama/.ollama/id_ed25519.pub  over to settings 

was working just fine 2 days ago

I believe i only restarted ollama, should that cause this or am i missing something? 

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.40

**Comment by ashokgit** [comment]
Update: I've narrowed down a potential cause. I had a running ollama instance running with 

docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama

 but somehow the 'ollama push' commands from terminal were being sent over to this ollama docker instance ... 
 
 so when i ran docker logs for some other purpose, i got this 
 time=2024-07-03T13:17:31.057Z level=ERROR source=images.go:963 msg="jwt token does not contain 3 parts"
time=2024-07-03T13:17:31.087Z level=INFO source=images.go:794 msg="error uploading blob: 400: {\"errors\":[{\"code\":\"ACCESS_DENIED\",\"message\":\"access denied\"}]}"
[GIN] 2024/07/03 - 13:17:31 | 200 |  804.021366ms |      172.17.0.1 | POST     "/api/push"
[GIN] 2024/07/03 - 13:26:42 | 200 |      24.522µs |      172.17.0.1 | HEAD     "/"
[GIN] 2024/07/03 - 13:26:42 | 200 |    1.015687ms |      172.17.0.1 | POST     "/api/copy"
[GIN] 2024/07/03 - 13:26:52 | 200 |      19.598µs |      172.17.0.1 | HEAD     "/"
time=2024-07-03T13:26:57.453Z level=ERROR source=images.go:963 msg="jwt token does not contain 3 parts"

**Comment by ashokgit** [comment]
Solved after stopping ollama docker instance

**Comment by Pravda77** [comment]
I am experiencing the exact same server-side error, `level=ERROR source=images.go:963 msg="jwt token does not contain 3 parts"`, but in a different scenario without Docker.

**My setup:**
- **OS:** MiniOS (a Debian-based Linux Live system)
- **Ollama Version:** 0.1.41
- **Environment:** Running the `ollama` binary directly from the shell, no Docker involved.

**Client/Server Behavior:**
- The client fails with the misleading error: `Error: pull model manifest: file does not exist`.
- The server logs the `jwt token does not contain 3 parts` error, but then incorrectly reports a `200 OK` for the `/api/pull` request.
- Basic network connectivity is fine (`curl` to `ollama.ai` works perfectly).

This confirms the JWT issue is not exclusively related to Docker and can be triggered on a standard Linux environment, possibly due to a specific OS configuration or networking stack.
