### ISSUE TITLE
Running Hugging Face Models

### ISSUE THREAD

**Issue by theainerd** [ollama/ollama#5489]
Hi team,

Can we load Hugging Face models directly using ollama?

**Comment by pdevine** [comment]
@theainerd do you mean something like being able to run `ollama run https://huggingface.co/path/to/model` or do you mean being able to import models from HF Safetensors?

For the first use case, it's really hard to do that because we don't support many of the models which are available on HF which results in a broken user experience. This is the case for llama.cpp right now. For the second use case, we actually do support converting many models from Safetensors, including Llama2/Llama3, Gemma, and Mistral/Mixtral based models. If you include the path in the `FROM` line of a model file, you can use `ollama create` to directly import the models into Ollama.

I'm going to go ahead and close the issue, but feel free to keep commenting. If I misunderstood something we can reopen.
