### ISSUE TITLE
Support glm3 and glm4

### ISSUE THREAD

**Issue by Forevery1** [ollama/ollama#5529]
Currently, llama.cpp has merged a PR for this model, which means that llama.cpp already supports gml3 and glm4. We hope to add support for this model @jmorganca 
https://github.com/ggerganov/llama.cpp/pull/8031

**Comment by jmorganca** [comment]
👀

**Comment by kiradzS** [comment]
Hope to update the support soon!

**Comment by loveyume520** [comment]
Hope the same

**Comment by taozhiyuai** [comment]
https://github.com/ollama/ollama/issues/5553. @jmorganca

**Comment by jmorganca** [comment]
Hi folks! https://ollama.com/library/glm4

**Comment by tobias-varden** [comment]
The model sometimes output a series of G;s
> User: Who is america's president?
As of my last update in early 2023, the President of the United States is Joe Biden. However, political offices
are subject to change, so it's always best to check the latest sources for the current officeholder.

> Today's date is 10th of July and in November there will be a new election/
Given that today's date is the 10th of July, if we're discussing an upcoming election in November, we would be
looking at either the midterm elections in the United States or another country's general election, depending on
the specific context.

> For the U.S., the next major election would typically be the midterm elections, which are held two years after a
presidential election year. Since the last presidential election was in November 2020 (which you mentioned as
"today"), the midterm elections for 2022 have already passed. Therefore, if we're talking about an election that
is more than six months away from now, it would be the next general election for president.

> The 2024 United States presidential election will take place on Tuesday, NovemberGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG

**Comment by cwegener** [comment]
> The model sometimes output a series of G;s `ollama run glm4:9b-chat-q4_K_M`
> 

https://github.com/ggerganov/llama.cpp/pull/8031#issuecomment-2219752905

**Comment by ciprianveg** [comment]
Can you please add also glm4 chat 1M?
