### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by psmoros** [ollama/ollama#5546]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@pyozzi-toss) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by pyozzi-toss** [comment]
Their contact information is ***@***.***

The person who contacted me is 'Michael Chiang ***@***.***>'.

2024년 7월 9일 (화) 오전 12:01, Pavlos ***@***.***>님이 작성:

**Comment by mchiang0610** [comment]
Hi @psmoros, thank you for the suggestion! It's a great idea that we will get to. We have hello@ollama.com and security@ollama.com for anyone to send in the security issues.  

Is this separate than the one submitted by @pyozzi-toss on June 26th? I've confirmed that one. 

We received the vulnerability report by @pyozzi-toss on Jun 26, 2024, 3:40 PM (EST). 

I acknowledged the receipt on Jun 26, 2024, 3:56 PM (EST). 

It has since been fixed. 

I would like to thank you both for the help! Feel free to reach out! 

(Closing this but feel free to re-open it again if needed or directly contact me at michael@ollama.com)

**Comment by pyozzi-toss** [comment]
hello. @psmoros 
Could @mchiang0610 help me get access to my huntr reports?

**Comment by psmoros** [comment]
Thanks Michael! We'll reach out :))

**Comment by pyozzi-toss** [comment]
Oh, I said it wrong.

I have access to my reports.
Michael didn't seem to be able to access my report, so he meant to ask if I
could help him.

2024년 7월 9일 (화) 오전 7:39, Pavlos ***@***.***>님이 작성:

**Comment by psmoros** [comment]
Oh don't worry we will handle it thank you :) @pyozzi-toss

**Comment by pyozzi-toss** [comment]
thanks! 😊

2024년 7월 9일 (화) 오전 7:45, Pavlos ***@***.***>님이 작성:
