### ISSUE TITLE
Raspberry Pi no longer loading models

### ISSUE THREAD

**Issue by bkev** [ollama/ollama#5674]
### What is the issue?

Previously I've been able to run models such as Gemma and Internlm2 on the raspberry pi and they have worked. But, in later version of Ollama I'm now blocked from running them. 

As far as I can tell, Ollama now checks RAM and doesn't load the model. Is there any override for this check? "Model requires more system memory than is available”. 

I know it's limited on the pi but these models did work, if a little slow, and it would be nice to be able to continue to use them. 

### OS

Linux

### Ollama version

0.2.3

**Comment by bkev** [comment]
So I can see this is due to a change in version 0.2.0

"Ollama will now return an error if the system does not have enough memory to run a model on Linux"

Is there an override for this (in the Ollama.service file for example)?

**Comment by rick-github** [comment]
I think the problem is this line:

https://github.com/ollama/ollama/blob/22c5451fc28b20dd83a389c49d9caf6a1e50a9e3/llm/server.go#L130

Because of the `min`, ollama will never load a model larger than the amount of RAM installed in the system, irrespective of how much swap is added.  With resource constrained platforms like the Pi, this prevents loading even moderately useful models.
