### ISSUE TITLE
`ollama run (modelname)` runs instruction-finetuned model

### ISSUE THREAD

**Issue by d-kleine** [ollama/ollama#5919]
I just have noticed that `ollama run llama3` runs ***Llama 3 8B Instruct*** (the instruction-finetuned variant) instead of ***Llama 3 8B***: 
https://ollama.com/library/llama3/blobs/6a0746a1ec1a

These are different models:
**Llama 3 8B**: https://huggingface.co/meta-llama/Meta-Llama-3-8B
**Llama 3 8B Instruct**: https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct

Would it be possible to fix this?

**Comment by rick-github** [comment]
I don't know if it's policy, but it seems that the plain model name in the ollama library usually references the finetuned model, and the base model is usually \<model\>:text or \<model\>:base, eg [llama3:text](https://ollama.com/library/llama3:text)

**Comment by d-kleine** [comment]
Oh, wow, thanks! Very intuitive from my pov...

**Comment by Cephra** [comment]
But it is indeed odd why there is a :text for [llama3](https://ollama.com/library/llama3/tags), but there isn't for [llama3.1](https://ollama.com/library/llama3.1/tags). Maybe this is indeed an oversight?

**Comment by gwillen** [comment]
I have been assuming that it's just because llama3.1 is still too new, and it takes time to do format conversion and quantization and so forth.

(Note that, in addition to defaulting to the instruct-tuned model, ollama also defaults to a 4-bit quantization of the model. I think this makes sense, because otherwise most people would waste a ton of bandwidth downloading the full-sized version, and then not be able to run it. But it's worth inspecting the specific quantization levels yourself; I don't recommend ever downloading the default option.)

**Comment by d-kleine** [comment]
> I have been assuming that it's just because llama3.1 is still too new, and it takes time to do format conversion and quantization and so forth.

Might be, but actually llama3.1 is already provided (llama3.1), and the instruction-finetuned variant most likely won't have a different architecture. So idk... And I would be surprised if this process isn't automated to some point tbh.

> (Note that, in addition to defaulting to the instruct-tuned model, ollama also defaults to a 4-bit quantization of the model.

Yeah, seems to be `q_4` by default
