### ISSUE TITLE
Second Disk Support

### ISSUE THREAD

**Issue by wioniqle-q** [ollama/ollama#5929]
I have a second disc that have large capacity but when try the I install ollama.exe (for windows) that install models directly USERS/USERNAME/.ollama installing

but I don't have any space on my C drive. So That I need to run for a on my second disc that I can download models into second disc and download the models to the second disc

**Comment by igorschlum** [comment]
> Information about default model directories and how to change that is available in the FAQ[1](#user-content-fn-1-3fb73fa52bea345d5617df590806ae09).
> 
> https://github.com/ollama/ollama/blob/8645076a71941d78a996e52cff65c794df6cdbcb/docs/faq.md?plain=1#L139-L149
> 
> ## Footnotes
> 1. https://github.com/ollama/ollama/blob/8645076a71941d78a996e52cff65c794df6cdbcb/docs/faq.md#where-are-models-stored [↩](#user-content-fnref-1-3fb73fa52bea345d5617df590806ae09)

**Comment by Bobbyjoness** [comment]
Hello idk why this issue is closed. I have the same problem. The installer on windows immediately installs on the c drive without allowing you to select an alternate location. Also a gui option to select alternate directory for models would also be useful imo. Although tbh I cant even install the program right now.
