### ISSUE TITLE
Distributed Computing: Run single large model on multiple machines

### ISSUE THREAD

**Issue by mrmiket64** [ollama/ollama#5983]
Hello dear Ollama team.

I'd like to request a new feature in Ollama that allows a single large model to be run across multiple machines for inference. This would enable users to take advantage of distributed computing to handle very large models that would exceed the memory capacity of a single machine.

That functionality could allow to:
- Make more accessible to run models like llama 3.1 405b 
- Distribute the load when running several smaller models to serve a large user base

Thank you for all of your great work, it is really making a difference for me.

All the Best
Miguel

**Comment by rick-github** [comment]
ollama use [llama.cpp](https://github.com/ggerganov/llama.cpp) for inference, so that's where the distributed computing needs to be implemented.  There have been attempts to do so, mainly by using the [MPI](https://www.geeksforgeeks.org/mpi-distributed-computing-made-easy/) framework but that work has languished recently.

**Comment by dhiltgen** [comment]
Lets track this via #4643
