### ISSUE TITLE
When processing long texts, it freezes and there is no response.

### ISSUE THREAD

**Issue by jiaguangqi** [ollama/ollama#6135]
### What is the issue?

I am using Ollama to run llama3.1:70b. When processing long texts, it freezes and there is no response. I have checked the server’s CPU, memory, and GPU usage, and they are all low. What could be the problem?

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.30

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) may help in debugging.

**Comment by igorschlum** [comment]
@jiaguangqi and please test with 0.3.3, ollama 0.1.3 is October, 13th 2023, unless you wanted to type 0.3.1

**Comment by jiaguangqi** [comment]
how to upgrade?



---Original---
From: "Igor ***@***.***&gt;
Date: Sat, Aug 3, 2024 05:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ollama/ollama] When processing long texts, it freezes and thereis no response. (Issue #6135)




 
@jiaguangqi and please test with 0.3.3, ollama 0.1.3 is October, 13th 2023, unless you wanted to type 0.3.1

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-upgrade-ollama

**Comment by pdevine** [comment]
@jiaguangqi what was happening was most likely a context shift. When the context fills up, part of the context has to be lopped off in order to keep processing. I don't remember the performance characteristics for the version you are using  though given that is almost a year ago 😅 

I'll close the issue for now, but feel free to keep commenting and we can reopen if you're still seeing a problem.
