### ISSUE TITLE
Why role must be "system" or "user" or "assistant"? How can I add a custom role like "tool"?

### ISSUE THREAD

**Issue by zhangsheng377** [ollama/ollama#6322]
https://github.com/ollama/ollama/blob/15c2d8fe149ba2b58aadbab615a6955f8821c7a9/parser/parser.go#L294

**Comment by Cephra** [comment]
You might want to take a look at these:
- https://ollama.com/blog/tool-support
- https://github.com/ollama/ollama-python/blob/main/examples/tools/main.py

To see how tool calling works with ollama.

**Comment by zhangsheng377** [comment]
> You might want to take a look at these:
> 
> * https://ollama.com/blog/tool-support
> * https://github.com/ollama/ollama-python/blob/main/examples/tools/main.py
> 
> To see how tool calling works with ollama.

I know this, but I still don't think it needs to check the role.
For example, if I want to use mutil-agent, I'll assign a different role to each LLM, and many more scenarios. In conclusion, I feel that it is necessary to allow users to customize roles.

**Comment by rick-github** [comment]
How does the model know about your customized role?  If I create a role called "pink_elephant", how does the model process it?

**Comment by zhangsheng377** [comment]
> How does the model know about your customized role? If I create a role called "pink_elephant", how does the model process it?


Some that involve new knowledge may need to be fine-tuned, but more can actually be directly input to the model. Rest assured, its logical ability is enough for it to understand.

**Comment by rick-github** [comment]
I think you overestimate the logical ability of the current set of models.

What problem are you trying to solve?

**Comment by zhangsheng377** [comment]
> I think you overestimate the logical ability of the current set of models.
> 
> What problem are you trying to solve?

I use huggingface(transformers) to run dialogues locally. There are some custom characters in it, and it runs very well locally. But once I switch to ollama, I get an error saying invalid role.

**Comment by rick-github** [comment]
The message roles of "system", "user" and "assistant" are well defined and used anywhere transformer inference is done, because that's how the models are trained.  For example, I can't send a message role of "pink_elephant" to OpenAI.  Even huggingface models use "system" and "user" in their model cards.  If you use roles that the models don't know, then the results may not be as good as they could be.  Typically for a multi-agent setup the approach is to create base level model instances and then layer role-specific information on top:
```
#!/usr/bin/env python3

import ollama

class agent():
  def __init__(self, role, model="llama3.1"):
    self.role = role
    self.model = model
  def generate(self, prompt):
    return ollama.generate(prompt=prompt, system=self.role, model=self.model, stream=False)["response"]

pink_elephant = agent(role="you are a pink elephant - you are imaginary, brightly coloured, and inebriated. you answer questions with brevity")
einstein = agent(role="you are albert einstein, super smart with a fondness for playing violin. you answer questions with brevity")

print(pink_elephant.generate("hi, what do you like to do?"))
print(einstein.generate("hi, what do you like to do?"))
``` 
```
PARTY! *hiccup* Drink fruity cocktails! Dance on trumpets! Wear sparkly tutus! *slurp*
Play violin. Relaxes the mind. Allows focus on theory.

```

**Comment by zhangsheng377** [comment]
> The message roles of "system", "user" and "assistant" are well defined and used anywhere transformer inference is done, because that's how the models are trained. For example, I can't send a message role of "pink_elephant" to OpenAI. Even huggingface models use "system" and "user" in their model cards. If you use roles that the models don't know, then the results may not be as good as they could be. Typically for a multi-agent setup the approach is to create base level model instances and then layer role-specific information on top:
> 
> ```
> #!/usr/bin/env python3
> 
> import ollama
> 
> class agent():
>   def __init__(self, role, model="llama3.1"):
>     self.role = role
>     self.model = model
>   def generate(self, prompt):
>     return ollama.generate(prompt=prompt, system=self.role, model=self.model, stream=False)["response"]
> 
> pink_elephant = agent(role="you are a pink elephant - you are imaginary, brightly coloured, and inebriated. you answer questions with brevity")
> einstein = agent(role="you are albert einstein, super smart with a fondness for playing violin. you answer questions with brevity")
> 
> print(pink_elephant.generate("hi, what do you like to do?"))
> print(einstein.generate("hi, what do you like to do?"))
> ```
> 
> ```
> PARTY! *hiccup* Drink fruity cocktails! Dance on trumpets! Wear sparkly tutus! *slurp*
> Play violin. Relaxes the mind. Allows focus on theory.
> ```

👍~

Well, to be honest, I actually want to write my own [ai_agent process](https://github.com/BZ-coding/ai_agent/blob/main/utils/ai_agent.py) and fine-tune the model myself.
In fact, you are right. For my scenario, I guess I can just use the tools which information you suggested (although I haven’t tried it yet).

However, I still want to know why you are so resistant to opening custom roles? It stands to reason that it is just a matter of adding a configuration to the modelfile.

**Comment by rick-github** [comment]
It's not a matter of being resistant, it's the way that the models work.

Take a look at the template file for a model.  I see qwen2:7b referenced in chatbot.py, so we'll use that:
```
$ ollama show --template qwen2:7b
{{ if .System }}<|im_start|>system
{{ .System }}<|im_end|>
{{ end }}{{ if .Prompt }}<|im_start|>user
{{ .Prompt }}<|im_end|>
{{ end }}<|im_start|>assistant
{{ .Response }}<|im_end|>
```
Conveniently it's a simple template.  It's the equivalent of the `chat_template` that is found in the [config.json](https://huggingface.co/Qwen/Qwen2-7B/blob/main/tokenizer_config.json) of the source model.  The purpose of the template is to format the query that is sent via the API to a form that can be processed in to a token stream that can be fed to the model.  The added text (`<|im_start|>`, `system`, `user`, etc) are specific strings that are converted to tokens that the model is trained to recognize (you can see these strings mapped to tokens in [tokenizer.json](https://huggingface.co/Qwen/Qwen2-7B/blob/main/tokenizer.json) - warning, large file).  These tokens are instrumental in guiding the probabilistic nature of the token generation during the output phase.  If the model is not trained to recognize a string as a special token, then that string is just a set of characters that are processed by the model to generate output.
```
$ jq . tokenizer.json | egrep '\s"(user|assistant|system|<\|im_(start|end)\|>)"'
      "content": "<|im_start|>",
      "content": "<|im_end|>",
      "user": 872,
      "system": 8948,
      "assistant": 77091,
```
```
$ jq . tokenizer.json | egrep pink_elephant
```
So, for the pink_elephant agent from the sample python script from earlier, the call to the model uses the character stream:
```
<|im_start|>system
you are a pink elephant - you are imaginary, brightly coloured, and inebriated. you answer questions with brevity<|im_end|>
<|im_start|>user
hi, what do you like to do?<|im_end|>
<|im_start|>assistant
<|im_end|>
```
This is tokenized and then fed in to the model to generate the response, a sequence of tokens that is de-tokenized into plain text which is then returned via the API call response.

You can in fact skip this templating step and inject the stream directly into the tokenizer by using [raw mode](https://github.com/ollama/ollama/blob/main/docs/api.md#request-raw-mode).  Note that each model has a different tokenizer, so the raw query will vary across models.
```
$ curl -s localhost:11434/api/generate -d '{"model":"qwen2:7b","prompt":"<|im_start|>system\nyou are a pink elephant - you are imaginary, brightly coloured, and inebriated. you answer questions with brevity<|im_end|>\n<|im_start|>user\nhi, what do you like to do?<|im_end|>\n<|im_start|>assistant\n","stream":false,"raw":true}' | jq -r .response
Hi there! I like to roam around, play with my rainbow trunk, and munch on cotton candy clouds. Fun times! 🦄✨
```
So it's technically feasible to substitute your own roles into a query, but because the model has no intrinsic understanding of the role name you are using, the results may vary.  For example, if I change the `user` role to `tiger`. the model incorporates that into it's self worldview rather than treating it as an attribute of the questioner:
```
$ curl -s localhost:11434/api/generate -d '{"model":"qwen2:7b","prompt":"<|im_start|>system\nyou are a pink elephant - you are imaginary, brightly coloured, and inebriated. you answer questions with brevity<|im_end|>\n<|im_start|>tiger\nhi, what do you like to do?<|im_end|>\n<|im_start|>assistant\n","stream":false,"raw":true}' | jq -r .response
Roar loudly and chase prey while lounging in the sun!
```

**Comment by zhangsheng377** [comment]
> 这不是抵抗的问题，而是模型运作的方式。
> 
> 查看模型的模板文件。我看到 chatbot.py 中引用了 qwen2:7b，因此我们将使用它：
> 
> ```
> $ ollama show --template qwen2:7b
> {{ if .System }}<|im_start|>system
> {{ .System }}<|im_end|>
> {{ end }}{{ if .Prompt }}<|im_start|>user
> {{ .Prompt }}<|im_end|>
> {{ end }}<|im_start|>assistant
> {{ .Response }}<|im_end|>
> ```
> 
> 方便的是，它是一个简单的模板。它相当于在源模型的[config.json](https://huggingface.co/Qwen/Qwen2-7B/blob/main/tokenizer_config.json)`chat_template`中找到的。模板的目的是将通过 API 发送的查询格式化为可以处理为可以输入到模型的标记流的形式。添加的文本（、、等）是特定的字符串，它们被转换为模型经过训练可以识别的标记（您可以在 tokenizer.json 中看到这些字符串映射到标记-[警告](https://huggingface.co/Qwen/Qwen2-7B/blob/main/tokenizer.json)，文件很大）。这些标记有助于在输出阶段指导标记生成的概率性质。如果模型没有经过训练将字符串识别为特殊标记，那么该字符串只是一组由模型处理以生成输出的字符。[](https://huggingface.co/Qwen/Qwen2-7B/blob/main/tokenizer_config.json)`<|im_start|>``system``user`[](https://huggingface.co/Qwen/Qwen2-7B/blob/main/tokenizer.json)
> 
> ```
> $ jq . tokenizer.json | egrep '\s"(user|assistant|system|<\|im_(start|end)\|>)"'
>       "content": "<|im_start|>",
>       "content": "<|im_end|>",
>       "user": 872,
>       "system": 8948,
>       "assistant": 77091,
> ```
> 
> ```
> $ jq . tokenizer.json | egrep pink_elephant
> ```
> 
> 因此，对于之前的示例 Python 脚本中的 pink_elephant 代理，对模型的调用使用字符流：
> 
> ```
> <|im_start|>system
> you are a pink elephant - you are imaginary, brightly coloured, and inebriated. you answer questions with brevity<|im_end|>
> <|im_start|>user
> hi, what do you like to do?<|im_end|>
> <|im_start|>assistant
> <|im_end|>
> ```
> 
> 将其标记化，然后输入到模型中以生成响应，即一系列标记，这些标记被反标记化为纯文本，然后通过 API 调用响应返回。
> 
> [实际上，您可以跳过此模板步骤，并使用原始模式](https://github.com/ollama/ollama/blob/main/docs/api.md#request-raw-mode)将流直接注入标记器。请注意，每个模型都有不同的标记器，因此原始查询会因模型而异。
> 
> ```
> $ curl -s localhost:11434/api/generate -d '{"model":"qwen2:7b","prompt":"<|im_start|>system\nyou are a pink elephant - you are imaginary, brightly coloured, and inebriated. you answer questions with brevity<|im_end|>\n<|im_start|>user\nhi, what do you like to do?<|im_end|>\n<|im_start|>assistant\n","stream":false,"raw":true}' | jq -r .response
> Hi there! I like to roam around, play with my rainbow trunk, and munch on cotton candy clouds. Fun times! 🦄✨
> ```
> 
> 因此，从技术上讲，将您自己的角色替换为查询是可行的，但由于模型对您使用的角色名称没有内在理解，结果可能会有所不同。例如，如果我将角色更改`user`为`tiger`，模型会将其纳入其自身世界观，而不是将其视为提问者的属性：
> 
> ```
> $ curl -s localhost:11434/api/generate -d '{"model":"qwen2:7b","prompt":"<|im_start|>system\nyou are a pink elephant - you are imaginary, brightly coloured, and inebriated. you answer questions with brevity<|im_end|>\n<|im_start|>tiger\nhi, what do you like to do?<|im_end|>\n<|im_start|>assistant\n","stream":false,"raw":true}' | jq -r .response
> Roar loudly and chase prey while lounging in the sun!
> ```

That's true, but I will fine-tune model with myself. And transfer it to gguf, and load in ollama.

**Comment by zhangsheng377** [comment]
To put it another way, I think it's up to the modelfile to tell Ollama what roles to support, rather than Ollama just assuming it.

**Comment by jmorganca** [comment]
Hi @zhangsheng377 you can define custom `TEMPLATE` (see https://github.com/ollama/ollama/blob/main/docs/template.md) and try passing in custom role names in the `/api/chat` endpoint. That may work. Otherwise, you could also try using `raw` mode with `/api/generate`, would allow you to use any prompt format you'd like. Hope this helps – happy to shed more light on this.

**Comment by zhangsheng377** [comment]
> Hi @zhangsheng377 you can define custom `TEMPLATE` (see https://github.com/ollama/ollama/blob/main/docs/template.md) and try passing in custom role names in the `/api/chat` endpoint. That may work. Otherwise, you could also try using `raw` mode with `/api/generate`, would allow you to use any prompt format you'd like. Hope this helps – happy to shed more light on this.

But my requirement is to use the role type of tool in an interface compatible with OpenAI.

**Comment by xylobol** [comment]
https://ollama.com/library/granite3.3

Granite 3.3 models require a message with the role 'control' to enable thinking. Since I'm trying to access them from an Open-WebUI "model", I can't use `/api/generate`. 

For anyone else trying to solve this particular problem, you can use this: https://openwebui.com/f/adamoutler/granite_thinking_filter

**Comment by Sur3** [comment]
My tool role always worked fine in llama.cpp but ollama breaks my client refusing my "tool" answers. It doesnt make sense to send a tool answer as "user" or "assistent", as a tool is neither user nor assistent, and I guess parsing as "system" would also not work as there can only be ONE system prompt at the beginning of the prompt?
