### ISSUE TITLE
Ollama embedding is slow

### ISSUE THREAD

**Issue by yuanjie-ai** [ollama/ollama#6414]
Ollama embedding is slow

**Comment by rick-github** [comment]
Example?

**Comment by pdevine** [comment]
@yuanjie-ai make certain you're using the new [batch embeddings endpoint](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings) instead of the older endpoint which could only generate a single embedding at a time.

Given a lack of detail in the issue though, I'm going to go ahead and close it. Feel free to comment with more details if you think it should be re-opened.
