### ISSUE TITLE
Manage output length?

### ISSUE THREAD

**Issue by nic0711** [ollama/ollama#6433]
Hi. Is it possible to manage the output length?
I use ollama with llama3.1-instruction-8q and fabric. 

My problem is that the output is too short and ends the last sentence unfinished. 

The biggest/longest output was 1200 characters...

Can I change this?
Thank you.

**Comment by pdevine** [comment]
@nic0711 you can extend the context length. In the CLI you can just type:
```
>>> /set parameter num_ctx 8192
```
Which would set the context length to 8192. You will need to have more VRAM (if you're using a GPU) in order to support a larger context otherwise some layers of the model may be offloaded onto your CPU. Llama3.1 can go up to a 128k context length.

**Comment by OfficiallyCrazy** [comment]
The man had asked for OUTPUT length not for INPUT. 

I find your answer inadequate.

**Comment by DraculaVladimir** [comment]
> [@nic0711](https://github.com/nic0711) you can extend the context length. In the CLI you can just type:
> 
> ```
> >>> /set parameter num_ctx 8192
> ```
> 
> Which would set the context length to 8192. You will need to have more VRAM (if you're using a GPU) in order to support a larger context otherwise some layers of the model may be offloaded onto your CPU. Llama3.1 can go up to a 128k context length.

The man had asked for OUTPUT length not for INPUT.

I find your answer inadequate.
