### ISSUE TITLE
404 one download

### ISSUE THREAD

**Issue by vorticalbox** [ollama/ollama#6472]
### What is the issue?

https://ollama.com/download/ollama-linux-amd64.tgz is returning a 404

### OS

Linux

### GPU

Nvidia

### CPU

Intel

**Comment by MaxJa4** [comment]
V0.3.7 changed the distribution of the Linux installation package to at tar.gz file. Since the docs are updated right away, but the new version is not released yet, you can't run the manual installation steps yet.

Use the old version of the instructions for now:

https://github.com/ollama/ollama/blob/896495de7b5814cca32ba83d2e9f2bf176ba98c8/docs/linux.md

Or just run the installation script.

**Comment by fenggaobj** [comment]
Maybe you can download it from the release section. The download link is:
https://github.com/ollama/ollama/releases/download/v0.3.7-rc5/ollama-linux-amd64.tgz

**Comment by Maltz42** [comment]
fenggaobj's direct link to v0.3.7-rc5 works, but older versions are now broken.  These links, for example:

https://github.com/ollama/ollama/releases/download/v0.3.6/ollama-linux-amd64.tgz
https://ollama.com/download/ollama-linux-amd64.tgz?version=0.3.6

**Comment by rick-github** [comment]
v0.3.6 is shipped as a binary program, not as a tgz: https://github.com/ollama/ollama/releases/download/v0.3.6/ollama-linux-amd64
