### ISSUE TITLE
Ollama can't import safetensor of mistral 7B v0.1

### ISSUE THREAD

**Issue by ZhoraZhang** [ollama/ollama#6566]
### What is the issue?

I have written modelfile: 
FROM /data/models/Mistral-7B-v0.1 (path of mistral's safetensor files)
I tried to import model using /api/create but failed.
{"error":"read /data/models/Mistral-7B-v0.1: is a directory"}

### OS

Linux

### GPU

Nvidia

**Comment by rick-github** [comment]
At a guess I'd say because the low-level `/api/create` doesn't have all of the extra processing that `ollama create` does.

[`Remote model creation must also create any file blobs, fields such as FROM and ADAPTER`](https://github.com/ollama/ollama/blob/main/docs/api.md#create-a-model:~:text=Remote%20model%20creation%20must%20also%20create%20any%20file%20blobs%2C%20fields%20such%20as%20FROM%20and%20ADAPTER)

**Comment by igorschlum** [comment]
What mistral v01 and not v03?

**Comment by pdevine** [comment]
@ZhoraZhang you need to create the blobs first as @rick-github mentioned. You can look in `cmd/cmd.go` to see how it is calling `api.CreateBlob()`.

I'm going to go ahead and close the issue.

**Comment by ZhoraZhang** [comment]
> 如前所述，您需要先创建 blob。您可以查看它如何调用 .`cmd/cmd.go``api.CreateBlob()`
> 
> 我将继续关闭该问题。

Thank you

**Comment by ZhoraZhang** [comment]
> Hi @ZhoraZhang Way mistral v01 and not v03?

Hello, because I fine-tuned mistral v0.1 before and tried to use different way to deploy.
