### ISSUE TITLE
Ollama model custom model download directory not running

### ISSUE THREAD

**Issue by aksk01** [ollama/ollama#6785]
### What is the issue?

In Ubuntu earlier Ollama downloaded models in home directory and can download multiple models but now it is downloading in /usr/share/ollama/.ollama/ directory only no matter what please fix this, and even after trying out the steps mentioned in the repository it does not run ollama properly. It should be like windows as it allows you to download in any custom path

### OS

Linux

### Ollama version

latest

**Comment by rick-github** [comment]
If it's downloading to /usr/share/ollama/.ollama it's because it's running as a service (/etc/systemd/system/ollama.service).    When it downloaded to the home directory, ollama had been started as a user process (`$ ollama serve`).  You can override the download location by editing the service file and [setting a new download location](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-set-them-to-a-different-location).  If you find this doesn't work for you, you will need to include more information: what you did, why you think it's not working, what error messages you received, [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues), etc.

**Comment by pdevine** [comment]
@rick-github 's answer is correct. I'll go ahead and close this, but @aksk01 we can reopen if the above steps didn't work.

**Comment by aksk01** [comment]
Yes the method @rick-github  suggested have worked... thanks, finally its resolved for me, the current manual installation of ollama also does the same as this method
