### ISSUE TITLE
slow

### ISSUE THREAD

**Issue by ayttop** [ollama/ollama#6806]
### What is the issue?

The program is very slow
3.10 ollama 

### OS

Windows

### GPU

Intel

### CPU

Intel

### Ollama version

3.10

**Comment by remco-pc** [comment]
your hardware ?

**Comment by cgimenez** [comment]
And what model are you using ? I’ve pushed my Mac M2 (64 GB RAM) to its limits just trying to use LLaMA 3.1:70B." - ollama went hard to sigkill

**Comment by pdevine** [comment]
You can use `ollama ps` to figure out if the model is loaded into CPU or GPU.

**Comment by tcreek** [comment]
That fact they list intel GPU is very telling on why it is very slow.

**Comment by ayttop** [comment]
lama3.1 8q
no viga
Unusually slow, I deleted the first one and reinstalled it, and the same problem.

**Comment by ayttop** [comment]
i7
64ram

**Comment by tcreek** [comment]
unless you have a modern nVidia or AMD GPU, it will continue to be slow

**Comment by remco-pc** [comment]
and what do you think is slow, can you think faster ?, my llama3.1:70B model is slow, like 12 minutes for a response, but i find it rather fast enough and workable, i can give it tasks in the future to solve

**Comment by pdevine** [comment]
Hi @ayttop , sorry this is going slow for you. It's because you're using CPU inference (which you can tell with `ollama ps`). I'm not certain what your GPU is, but the Intel GPUs unfortunately aren't supported (yet). There are a number of issues already around supporting that, so I'm going to go ahead and close this issue (like #1590) so I'll go ahead and close this issue.
