### ISSUE TITLE
Jetson CUDA error

### ISSUE THREAD

**Issue by jarek7777** [ollama/ollama#6999]
### What is the issue?

I' ve built Ollama from source to run with CUDA  but unfortunately it doesn't start any more, I think since version 0.3.10 it's the same error. Before 0.3.10 everything was fine I was able to build ollama with CUDA and run any model, but now even smallest model 1b is crashing

I have the same Jetpack 6.0 with CUDA 12.2.140.

Error: llama runner process has terminated: CUDA error: the resource allocation failed
  current device: 0, in function cublas_handle at ollama/llm/llama.cpp/ggml/src/ggml-cuda/common.cuh:644
  cublasCreate_v2(&cublas_handles[device])
ollama/llm/llama.cpp/ggml/src/ggml-cuda.cu:102: CUDA error

### OS

Linux

### GPU

Nvidia, Other

### CPU

Other

### Ollama version

0.3.12

**Comment by dhiltgen** [comment]
These sorts of errors on Jetsons are usually the result of trying to use the discrete GPU (sbsa) cuda library instead of the Jetpack specific cuda library.  Depending on how you're building/installing, you might have accidentally wound up with our dGPU cuda library in your path. 

Once we get #6925 merged, our official builds will bundle the jetpack 5 and 6 libraries and wire things up at runtime correctly.
