### ISSUE TITLE
Docker image size is over a GB larger than 0.3.10

### ISSUE THREAD

**Issue by codefromthecrypt** [ollama/ollama#7074]
### What is the issue?

I noticed some changelog in reducing docker image size, but when looking at darwin/arm64, it is significantly larger than 0.3.10. This may also apply to others. Can you mention if this is an accident or intent?

```
ollama/ollama                                   0.3.12           443040bf2568   6 days ago      3.22GB
ollama/ollama                                   0.3.11           580b37f3291e   13 days ago     3.22GB
ollama/ollama                                   0.3.10           a6cc2736bd5c   3 weeks ago     1.92GB
```

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.3.12

**Comment by dhiltgen** [comment]
This is due to a space vs. time trade-off.

On Linux, Ollama carries LLM runner executables and dependent libraries as compressed payloads inside the main executable, and extracts them at startup into /tmp.  This can take 5-20s depending on the CPU and I/O performance of the system.  For long running systems, this overhead is negligible.  For containers which are often ephemeral, this extra delay at startup can be more impactful.  In 0.3.11 we adjusted our container build to carry these executables and dependent libraries directly in the container root filesystem ready to execute, which makes the container startup less than a second in most cases.  When you view the image sizes in docker, it's reporting the uncompressed sizes of the filesystem.  This masks the compressed binaries/libraries inside the 0.3.10 which are immediately extracted upon startup and occupy filesystem space in the running container.  If you look at the compressed sizes of the images they're nearly identical, so download times from docker hub should be ~identical.

**Comment by codefromthecrypt** [comment]
Thanks, FWIW I'm ok with it, as I tend to use ollama directly in CI, not via docker, and tiny models.

However, there are integration tests use ollama via docker (e.g. testcontainers) and so now this is a larger, and of course on slow networks, demos etc this is more visible than most places. That releases aren't daily compensates also. Main thing was understanding if this was an oversight or intent, and seems intent. Thanks for the answer.

**Comment by dhiltgen** [comment]
The images are downloaded compressed, and once compressed, the sizes between these versions are very close, so you shouldn't see a significant impact on transfer time to get the image loaded into a system.

**Comment by codefromthecrypt** [comment]
Thanks again for clarifying the mechanics about transfer size. I'll mention that to the person who asked me.
