### ISSUE TITLE
Make target audience clearer on website/in repository README

### ISSUE THREAD

**Issue by victorb** [ollama/ollama#7116]
Currently, it seems like Ollama is mostly geared towards developers and adjacent audiences, yet that isn't 100% clear on the website or in the repository README.

This results with many end users who might be better served by other tooling, give Ollama a try regardless, even though it might be overly technical compared to their knowledge, expertise and expectation.

In many cases these users end up confused and frustrated as they'll wade into deep technical waters without having the prerequisite understanding first. 

One potential fix for this is to make it explicitly clear that Ollama is made for developers and alike, on the website and in the repository README.

**Comment by victorb** [comment]
> just a simple pip install open-webui

This is simple for you and I, but for someone who never opened a terminal before? I don't think it's "simple" for them.

So one baseline knowledge for doing that, would be to have basic knowledge of terminals. Could you agree with that?

**Comment by hg0428** [comment]
> > just a simple pip install open-webui
> 
> This is simple for you and I, but for someone who never opened a terminal before? I don't think it's "simple" for them.
> 
> So one baseline knowledge for doing that, would be to have basic knowledge of terminals. Could you agree with this?

Or this: https://pinokio.computer/item?uri=https://github.com/pinokiofactory/open-webui

**Comment by victorb** [comment]
> Or this: https://pinokio.computer/item?uri=https://github.com/pinokiofactory/open-webui

But if Ollama is so easy to use for users without any technical expertise, why would you need something like pinokio to make it easier?

It seems to me that pinokio's target audience are users who want a "one-click = setup complete" experience with a GUI and everything, that gives them everything they need out of the box. Which Ollama isn't, and that's OK, not everything has to be made for that sort of end-user.

I only created this issue so expectations can be set up front.

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/pull/7067

**Comment by victorb** [comment]
So there seems to be some confusion about what is being proposed here (from at least one person in the Discord), so thought I'd clear things up a bit:

1. I'm not proposing to restrict the usage of Ollama in any way (it's not "gatekeeping")
2. The motivation for this is to help users better determine whether the tool is suitable for their expertise level, so users can make informed choices
3. Many projects explicitly state their intended audience to avoid misunderstandings and ensure that users know what to expect before diving in, which helps both the users (by avoiding frustration) and the maintainers (by reducing the number of inappropriate issues or support requests)

**Comment by pdevine** [comment]
Hey @victorb, I appreciate the comment! My take on this (and the intention of Ollama all along) is to open up LLMs to as many people as possible.

Before we launched (back in July last year) it was really hard for anyone outside of AI researchers to use Open Source LLMs just because the knowledge gap was so large. You needed to know how to download the correct model, you needed to know python or how to compile something on the command line, and you needed to know how to set up your GPU and the drivers for it! I think we've done a pretty good job getting rid of a lot of those barriers, although you're right, that the terminal for some people can still be somewhat daunting.

That said, I really don't want to try and claim whom Ollama is "for" and "not for". I think that ends up being problematic because in some sense everyone is a "developer". The reason why they're trying out Ollama is probably because of some dissatisfaction with the "cloud" (i.e. Closed Source) LLMs to begin with. I also think if you made it far enough to get to the README in the GitHub repo you're probably skilled enough to at least _try_ it. The last thing I would say is that this project is still pretty early on, and I would hate for people to get the impression that we can't make it even easier for people to use.

**Comment by pdevine** [comment]
@victorb I'm going to go ahead and close this, but feel free to keep commenting.
