### ISSUE TITLE
0.4.0rc0 arm64 andro termux compile error

### ISSUE THREAD

**Issue by fxmbsw7** [ollama/ollama#7293]
### What is the issue?

the earlier worked easy , `go generate ./...` and `go build .`

whats the new style ? gcc .c instead go ?
readme doesnt seem to contain about compilement

i run `go generate ./...` it returns
ill retry w/o go

```~/ollama-0.4.0-rc0 $ go generate ./...
<rm cmd removed for discord>
make -f make/Makefile.default
make[1]: Entering directory '/data/data/com.termux/files/home/ollama-0.4.0-rc0/llama'
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
GOARCH=arm64 go build -buildmode=pie "-ldflags=-w -s \"-X=github.com/ollama/ollama/version.Version=\" \"-X=github.com/ollama/ollama/llama.CpuFeatures=\" " -trimpath   -o /data/data/com.termux/files/home/ollama-0.4.0-rc0/llama/build/linux-arm64/runners/cpu/ollama_llama_server ./runner
# github.com/ollama/ollama/llama
ggml-quants.c:4023:88: error: always_inline function 'vmmlaq_s32' requires target feature 'i8mm', but would be inlined into function 'ggml_vec_dot_q4_0_q8_0' that is compiled without support for 'i8mm'
ggml-quants.c:4023:76: error: always_inline function 'vmmlaq_s32' requires target feature 'i8mm', but would be inlined into function 'ggml_vec_dot_q4_0_q8_0' that is compiled without support for 'i8mm'
ggml-quants.c:4023:64: error: always_inline function 'vmmlaq_s32' requires target feature 'i8mm', but would be inlined into function 'ggml_vec_dot_q4_0_q8_0' that is compiled without support for 'i8mm'
ggml-quants.c:4023:52: error: always_inline function 'vmmlaq_s32' requires target feature 'i8mm', but would be inlined into function 'ggml_vec_dot_q4_0_q8_0' that is compiled without support for 'i8mm'
make[1]: *** [make/Makefile.default:27: /data/data/com.termux/files/home/ollama-0.4.0-rc0/llama/build/linux-arm64/runners/cpu/ollama_llama_server] Error 1
make[1]: Leaving directory '/data/data/com.termux/files/home/ollama-0.4.0-rc0/llama'
make: *** [Makefile:41: default] Error 2
llama/llama.go:3: running "make": exit status 2```

### OS

Linux

### GPU

Other

### CPU

Other

### Ollama version

0.4.0rc0

**Comment by dhiltgen** [comment]
I think we'll need to move https://github.com/ollama/ollama/blob/main/llama/llama.go#L37-L38 `-D__ARM_FEATURE_MATMUL_INT8` behind a go build tag, and then add some smarts to the makefile to detect arm architecture somehow, then adjust tags accordingly.

**Comment by fxmbsw7** [comment]
sounds like whats needed
but plz also make this build feature include more , like the D ARM FMA and really all opts .. one two i did somewhen enable and it showed them then on
( i did enable all i can find , and some made it )

greets ..

**Comment by yashasnadigsyn** [comment]
any updates on this? downloading and building ollama in termux gives me the same error as above.

**Comment by fxmbsw7** [comment]
no
u need , after checking out , delete that int8 word ( till with last space
of last word ) on both mentioned lines
then compile ...

**Comment by fxmbsw7** [comment]
i made it work by adding the march 8.6 a but without sve
im looking further into opts

**Comment by fxmbsw7** [comment]
-march=armv8.7-a works well
why dont u add -march=armv8-a or the right equivalent for it on both arm64 linux targets ? then itd work ? no one compiles for v7 as many are 32b .. i think ..

**Comment by olamarvel** [comment]
Pls contrary to what people said that this fix would make termux work, it doesn't on my phone. I have spent hour trying every fix I found so I decide to seek help.

Was it intentional for armv8l to be unsupported cause I keep getting this.


> `cmd/interactive.go:4:2: package cmp is not in GOROOT (/usr/lib/go-1.19/src/cmp)
envconfig/config.go:5:2: package log/slog is not in GOROOT (/usr/lib/go-1.19/src/log/slog)
llama/llama.go:95:2: package slices is not in GOROOT (/usr/lib/go-1.19/src/slices)
../go/pkg/mod/golang.org/x/crypto@v0.31.0/curve25519/curve25519.go:13:8: package crypto/ecdh is not in GOROOT (/usr/lib/go-1.19/src/crypto/ecdh)
server/download.go:11:2: package math/rand/v2 is not in GOROOT (/usr/lib/go-1.19/src/math/rand/v2)
GOARCH=armv8l go build "-ldflags=-w -s \"-X=github.com/ollama/ollama/version.Version=459d822-dirty\"  " -trimpath  -o ollama .
go: unsupported GOOS/GOARCH pair linux/armv8l
make[1]: *** [make/Makefile.ollama:13: ollama] Error 2
make: *** [Makefile:51: exe] Error 2
root@localhost:~/ollama# cd llama
root@localhost:~/ollama/llama# nano llama.go          root@localhost:~/ollama/llama# cd ../
root@localhost:~/ollama# make
cmd/interactive.go:4:2: package cmp is not in GOROOT (/usr/lib/go-1.19/src/cmp)
envconfig/config.go:5:2: package log/slog is not in GOROOT (/usr/lib/go-1.19/src/log/slog)
llama/llama.go:95:2: package slices is not in GOROOT (/usr/lib/go-1.19/src/slices)
../go/pkg/mod/golang.org/x/crypto@v0.31.0/curve25519/curve25519.go:13:8: package crypto/ecdh is not in GOROOT (/usr/lib/go-1.19/src/crypto/ecdh)
server/download.go:11:2: package math/rand/v2 is not in GOROOT (/usr/lib/go-1.19/src/math/rand/v2)`


So I don't stress my self any longer. 
Thank you.

**Comment by fxmbsw7** [comment]
it looks some packages are missing
plz try my script , it includes some go get cmds and recursive get's
just a try .. im no go pro ..

http://0x0.st/8sgT.sh

**Comment by fxmbsw7** [comment]
i dunno arm8l , i use arm 8.7 a in the script

**Comment by olamarvel** [comment]
> it looks some packages are missing
> plz try my script , it includes some go get cmds and recursive get's
> just a try .. im no go pro ..
> 
> http://0x0.st/8sgT.sh

Ok I would try it.
Thanks

**Comment by olamarvel** [comment]
> it looks some packages are missing
> plz try my script , it includes some go get cmds and recursive get's
> just a try .. im no go pro ..
> 
> http://0x0.st/8sgT.sh

I go 
`error: 5636 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
8sgT.sh: line 19: cd: /data/data/com.termux/files/home/ollama.3336986989: No such file or directory

err :  cant cd into '/data/data/com.termux/files/home/ollama.3336986989'
 ran for 105 seconds .. bye ..`

**Comment by fxmbsw7** [comment]
looks like a git incomplete error ?
