### ISSUE TITLE
submitting corrections to models.

### ISSUE THREAD

**Issue by ht990332** [ollama/ollama#7530]
### What is the issue?

Hello. I am using LLama3.2 and I asked it an RXJS question. The answer was clear and pleasantly complete but there was a big mistake in the answer. Citation to corrections can be found on RXJS documentation. How do I submit corrections to the model's answers?

### OS

Linux

### GPU

Intel

### CPU

Intel

### Ollama version

0.3.14

**Comment by rick-github** [comment]
A model's information is fixed.  You can include updates by adding a layer on top (eg, RAG or fine-tuning) that uses fresher data sources, but the mistakes that the model was trained on can't be updated.

**Comment by pdevine** [comment]
Unfortunately there's no real feedback mechanism to get this data back to the model creators. You can of course fine tune a model to give it different properties, although we don't have fine tuning yet in Ollama (although you can take a fine tuned adapter that you have created and use it in Ollama).

Thank you for submitting the issue, but I'm going to go ahead and close the issue since there's not much we can do here.
