### ISSUE TITLE
Performance Impact of Scaling a 70B Model Across Multiple A100 GPUs and Further Speed Optimization

### ISSUE THREAD

**Issue by gslin1224** [ollama/ollama#7648]
Hi guys,
I have a question regarding the performance impact and potential optimizations for distributing a large model across multiple GPUs. Specifically:

When running a 70B parameter model, how does the speed compare when distributed across two A100 GPUs versus four A100 GPUs?
In general, does adding more GPUs consistently result in faster performance for such a large model, or are there potential diminishing returns due to factors like communication overhead?
Are there additional techniques or configurations within the Ollama framework (or recommended practices) that can further optimize or increase the speed when using multiple GPUs?
Thank you for your guidance and any insights you can provide to help enhance model performance!

**Comment by rick-github** [comment]
Inference with LLMs is, by the nature of LLMs, a serialized operation.  They're composed of a series of layers, and computation in one layer needs to be completed before its output can be fed in to the next layer.  This means that for an individual completion, multiple GPUs doesn't confer any increase in token generation.  In fact, the token generation rate decreases, as the CPU/PCI interface is a bottleneck as intermediate results get moved from one GPU to the next.  For example, llama3.1:70b on 4xA100s:
| #GPUs | Tokens/s|
|---|---|
|1 | 24.21 ± 0.018 |
| 2 | 22.66 ± 0.012 |
| 3 | 20.21 ± 0.012 |
| 4 |  20.14 ± 0.010 |

If you are doing multiple concurrent queries (`OLLAMA_NUM_PARALLEL`), then multiple GPUs can help, as GPU0 can process query 1 with the first half of the layers of the model while GPU1 processes query 2 with the second half.  The problem is that you can't control the scheduling of queries on the GPUs or how quickly they complete their processing on a segment of the model, so sometimes you get both queries being queued onto the same GPU.

One approach to maximizing performance is to run one copy of a model per GPU, by using multiple ollama servers and binding them to a specific GPU using `CUDA_VISIBLE_DEVICES`, and then run a load balancing proxy in front to present a unified interface (eg [litellm](https://github.com/BerriAI/litellm), [ollama_proxy](https://github.com/ParisNeo/ollama_proxy_server), [nginx](https://github.com/ollama/ollama/issues/7570#issuecomment-2464469733)).  Unfortunately, a 70b model might be too large for this, eg llama3.1:70b needs about 42G, which doesn't quite squeeze into a 40GB A100.  The bits that don't fit on the GPU then use CPU for inference, which is slower.  There is a hack though, if the system supports Nvidia's fallback memory.  I believe this is enabled by default on Windows for supported GPUs, Linux users need to set `GGML_CUDA_ENABLE_UNIFIED_MEMORY=1` in the server environment.  You can overallocate layers onto a GPU (https://github.com/ollama/ollama/issues/7629#issuecomment-2470280098) and the GPU will use system RAM for the bits that don't fit. Be aware that using this approach for too much of the model (ie large model or large context) can have a large performance impact (https://github.com/ollama/ollama/issues/7584#issuecomment-2466715900)

**Comment by gslin1224** [comment]
Hi @rick-github,

Thank you again for your detailed response and helpful suggestions. Does this mean there are no other effective ways to significantly enhance inference speed? Also, is Ollama inherently slower in inference performance compared to VLLM or Tensor RT LLM?

Thanks again for your guidance!

**Comment by rick-github** [comment]
To my knowledge, there's no way to significantly enhance inference speed for a single completion in ollama.

There are cases where multiple GPUs can be used to do parallel matrix ops in a single layer, which would increase inference speed.  The [PR](https://github.com/ggerganov/llama.cpp/pull/1703) that implemented multi-GPU support in ollama claims to do this, but I've never seen this make a difference in practice.  This could come down to sub-optimal configuration, as there are some options (eg [`[u]batch-size`](https://github.com/ggerganov/llama.cpp/blob/master/examples/main/README.md#batch-size), [`split-mode`](https://github.com/ggerganov/llama.cpp/tree/master/examples/server#:~:text=%2Dsm%2C%20%2D%2D-,split%2Dmode,-%7Bnone%2Clayer%2Crow)) which allow some tuning.  I experimented briefly some time ago but didn't see any improvement at the time.

When I'm concerned about performance, I usually focus on model selection, managing context size, and various options like `OLLAMA_NUM_PARALLEL` and `OLLAMA_FLASH_ATTENTION`.  There's not much in the way of knobs to be twiddled in ollama.

Other inference implementations may perform differently, I haven't conducted benchmarks across other servers so I can't speak to that.  It's on my TODO list though.

**Comment by gslin1224** [comment]
@rick-github ok, thanks a lot for your useful response!

**Comment by Readon** [comment]
> To my knowledge, there's no way to significantly enhance inference speed for a single completion in ollama.
> 

I have tested vLLM with AWQ quantization, which could utilize GPU in 100% load. And single sequence generation is almost 70% faster. 
However, it could not support fast model switching.

**Comment by PrimosK** [comment]
Hi guys,

I did some tests recently with:
- Model used: [mistral-small:24b-instruct-2501-q4_K_M](mistral-small:24b-instruct-2501-q4_K_M) (`32k context`)
- Various numbers of RTX 4090
- Making 100 requests (4 in parallel / so 4 threads)

The key point is that the model fits comfortably within the RTX 4090's VRAM.

**1. TEST (1x RTX 4090)**

1. Other settings: (defaults)
2. Token eval rate: 55,6 token/s
3. VRAM utilization: 22GB / 24GB
4. GPU processor utilization (during inference): **~90%**
5. Time to complete 100 requests: **212 seconds**

**2. TEST (4x RTX 4094)**

1. Other settings: OLLAMA_NUM_PARALLEL=4
2. Token eval rate: 46,09 token/s
3. VRAM utilization: 19GB / 24GB, 18 / 24GB, 18 / 24GB, 18/24GB
4. GPU processor utilization (during inference): **~25%**
5. Time to complete 100 requests: **214 seconds**

Surprisingly, there is virtually no improvement for the end user when doing 2. test. Throughput seems to be the same in both cases.  The most noticeable thing is that in the case of the second test, the GPUs are only ~25% utilized (so roughly `number of total GPUs / 4`).

WRT:
_One approach to maximizing performance is to run one copy of a model per GPU, by using multiple ollama servers and binding them to a specific GPU using CUDA_VISIBLE_DEVICES, and then run a load balancing proxy in front to present a unified interface (eg [litellm](https://github.com/BerriAI/litellm), [ollama_proxy](https://github.com/ParisNeo/ollama_proxy_server), https://github.com/ollama/ollama/issues/7570#issuecomment-2464469733)._

@rick-github:  Is this approach necessary even if the model fits nicely into a single GPU? With `4x GPUs` and `OLLAMA_NUM_PARALLEL=4`, I would have expected Ollama to load the entire model onto each `GPU` and distribute the workload accordingly. Is my understanding incorrect?

**Comment by smartG666** [comment]
> 嗨，大家好，
> 
> 我最近做了一些测试：
> 
> * 使用型号：mistral-small:24b-instruct-2501-q4_K_M ( `32k context`)
> * 各种 RTX 4090 数量
> * 发出 100 个请求（4 个并行/即 4 个线程）
> 
> 关键在于该模型能够轻松适配 RTX 4090 的 VRAM。
> 
> **1.测试（1x RTX 4090）**
> 
> 1. 其他设置：（默认）
> 2. 代币评估率：55,6 token/s
> 3. VRAM 使用率：22GB / 24GB
> 4. GPU 处理器利用率（推理期间）：**~90%**
> 5. 完成100个请求的时间：**212秒**
> 
> **2.测试（4x RTX 4094）**
> 
> 1. 其他设置：OLLAMA_NUM_PARALLEL=4
> 2. 代币评估率：46,09 代币/秒
> 3. VRAM 利用率：19GB / 24GB、18 / 24GB、18 / 24GB、18/24GB
> 4. GPU 处理器利用率（推理期间）：**~25%**
> 5. 完成100个请求的时间：**214秒**
> 
> 令人惊讶的是，在进行第 2 项测试时，最终用户几乎没有任何改进。两种情况下的吞吐量似乎相同。最值得注意的是，在第二次测试中，GPU 的利用率仅为约 25%（大致如此`number of total GPUs / 4`）。
> 
> WRT： _最大化性能的一种方法是每个 GPU 运行一个模型的副本，通过使用多个 ollama 服务器并使用 CUDA_VISIBLE_DEVICES 将它们绑定到特定的 GPU，然后在前面运行负载平衡代理以呈现统一的接口（例如[litellm](https://github.com/BerriAI/litellm)、[ollama_proxy](https://github.com/ParisNeo/ollama_proxy_server)、[#7570（评论）](https://github.com/ollama/ollama/issues/7570#issuecomment-2464469733)）。_
> 
> [@rick-github](https://github.com/rick-github)：即使模型可以很好地适应单个 GPU，这种方法是否必要？有了`4x GPUs`和`OLLAMA_NUM_PARALLEL=4`，我原本希望 Ollama 将整个模型加载到每个 GPU 上`GPU`并相应地分配工作负载。我的理解是否不正确？

I have encountered the same problem. I hope you have solved it. I am looking forward to your answer.
