### ISSUE TITLE
Have start model downloading after internet disconnect

### ISSUE THREAD

**Issue by mosquet** [ollama/ollama#7688]
## Description
When internet connection is lost during model download, the process starts again from 0% instead of resuming from the interrupted point.

## Current Behavior
- Download fails on connection loss
- When connection restored, download restarts from 0%
- All previous download progress is lost

## Expected Behavior
- Download should pause when connection lost
- Should resume from previous progress when reconnected
- Implement proper download state tracking

## Technical Considerations
- Need download progress persistence
- Connection state monitoring
- Resume capability implementation

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

Just updated now

**Comment by rick-github** [comment]
The current behaviour is to resume from the previous point when `ollama pull model` is run again.  However, if you restart the ollama server, one of the first things it does is do a housekeeping sweep and cleans up any extraneous files.  So the expected behaviour is met if you don't restart the server.

**Comment by mosquet** [comment]
thanks checking the current update everything is fixed
