### ISSUE TITLE
Less available memory than expected

### ISSUE THREAD

**Issue by tie-pilot-qxw** [ollama/ollama#7996]
### What is the issue?

I'm using a 4060 laptop GPU, which has 8GB of memory. However, from the log, it showed that
`library=cuda variant=v12 compute=8.9 driver=12.7 name="NVIDIA GeForce RTX 4060 Laptop GPU" total="8.0 GiB" available="6.9 GiB"`
That's quite strange for from `nvidia-smi`
![image](https://github.com/user-attachments/assets/f7e61eb4-ee66-4927-aa71-295a095c5bb0)
Actually, when I tried to run llama3.2 3b fp16, ollama offloads 10% of the layers to the CPU, while from `ollama ps`, the needed memory is 7.9GB, which should be able to fit in the GPU memory

### OS

WSL2

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.4.7

**Comment by fxmbsw7** [comment]
disable hard apps in autostart , disable graphica bling blinng , reboot - to clear memory and start less gpu mem eating apps
then try ollama

**Comment by tie-pilot-qxw** [comment]
> try if u can drive ur laptop or monitor via igpu , and leave the nv gpu only to ollama

I have set the laptop only to use the igup, however, ollama still shows that only 6.9GB is available while both the task manager and the nvidia-smi tell me all the 8GB are available

**Comment by fxmbsw7** [comment]
stuff seems using it

1 look in nv tool ( i dunno name i dont have nvidia since long )
what it says

2 go windows settings > system > display
in one of the two middle tabs
theres apps to select

u got windows btw ?
select all power saver
.. maybe add ollama that ollama that runs
process viewer > details , rightclick on the ollama and in menu should be '
go to directory '
then add this ollama as performance

50 50 chance

**Comment by rick-github** [comment]
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) and the output of `nvidia-smi -q` may aid in debugging.
